import { Template } from '@/types';

export const marketingTemplates: Template[] = [
    {
        id: 'marketing_campaign_wizard',
        name: '📣 Chiến dịch Marketing',
        icon: '📣',
        description: 'Multi-step wizard tạo Campaign Brief với governed packet và live path để đối soát',
        category: 'marketing',
        difficulty: 'medium',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Campaign Brief', 'Channel Strategy', 'Content Calendar', 'Ad Copy'],
    },
    {
        id: 'seo_audit',
        name: 'Kiểm tra SEO',
        icon: '🔎',
        description: 'Đánh giá website về Technical SEO, On-page, Off-page',
        category: 'marketing',
        fields: [
            { id: 'url', type: 'text', label: 'URL Website', placeholder: 'https://example.com', required: true, section: 'required', hint: 'URL trang chủ hoặc trang quan trọng nhất', example: 'https://shopx.vn' },
            { id: 'industry', type: 'text', label: 'Ngành/Lĩnh vực', placeholder: 'VD: E-commerce, SaaS, Blog...', required: true, section: 'required', hint: 'Ngành kinh doanh để AI đánh giá đúng bối cảnh', example: 'SaaS B2B — quản lý dự án' },
            { id: 'keywords', type: 'textarea', label: 'Target Keywords', placeholder: 'Các từ khóa đang target', required: false, rows: 2, section: 'advanced', hint: 'Mỗi từ khóa một dòng, kèm search volume nếu có', example: 'quản lý dự án online (2.4K)\nproject management tool (18K)' },
            { id: 'competitors', type: 'text', label: 'Đối thủ chính', placeholder: '2-3 website đối thủ', required: false, section: 'advanced', hint: 'URL của 2-3 đối thủ cạnh tranh trực tiếp', example: 'asana.com, monday.com' },
        ],
        intentPattern: `INTENT:
Tôi muốn audit SEO cho website [url].

INDUSTRY: [industry]
TARGET KEYWORDS: [keywords]
COMPETITORS: [competitors]

OUTPUT FORMAT:
- Technical SEO Report → On-Page Analysis → Content Quality Score → Priority Issues → Action Plan

SUCCESS CRITERIA:
- Đánh giá Technical SEO (SSL, speed, mobile)
- Đánh giá On-page SEO (title, meta, content)
- Đánh giá Off-page SEO (backlinks)
- Xác định priority issues`,
        outputExpected: ['Technical SEO Report', 'On-Page Analysis', 'Content Quality Score', 'Priority Issues', 'Action Plan'],
        outputTemplate: `## SEO Audit Output

## 1. Technical SEO Report
| Check | Status | Priority |
| --- | --- | --- |

## 2. On-Page Analysis

## 3. Content Quality Score

## 4. Priority Issues

## 5. Action Plan`,
        difficulty: 'medium',
        sampleOutput: `# SEO Audit Report: shopx.vn

## Overall SEO Score: 67/100 ⚠️

## Technical SEO
| Check | Status | Priority |
|-------|--------|----------|
| SSL Certificate | ✅ Valid | — |
| Mobile Responsive | ✅ Pass | — |
| Page Speed (Mobile) | ⚠️ 3.2s | High |
| Core Web Vitals | ❌ LCP 4.1s | Critical |
| Sitemap.xml | ✅ Present | — |
| Robots.txt | ⚠️ Blocking /api | Medium |

## On-Page Analysis
- **Title Tags:** 12/20 pages optimized ⚠️
- **Meta Descriptions:** 8/20 missing ❌
- **H1 Tags:** Duplicate H1 on 3 pages ⚠️
- **Image Alt Text:** 45% missing ❌

## Top Priority Actions
1. 🔴 Fix Core Web Vitals (LCP) — optimize hero images
2. 🔴 Add missing meta descriptions
3. 🟡 Optimize page load speed — enable compression
4. 🟡 Fix duplicate H1 tags
5. 🟢 Add alt text to images

## Keyword Rankings
| Keyword | Position | Volume | Trend |
|---------|----------|--------|-------|
| quản lý dự án online | #12 | 2.4K | ↗️ |
| project management tool | #34 | 18K | → |

---
*Generated by CVF Platform*
`,
    },
    {
        id: 'copywriting_evaluation',
        name: 'Đánh giá Copywriting',
        icon: '✏️',
        description: 'Đánh giá và cải thiện marketing copy',
        category: 'marketing',
        difficulty: 'medium',
        fields: [
            { id: 'copy', type: 'textarea', label: 'Copy Text', placeholder: 'Paste đoạn copy cần đánh giá...', required: true, rows: 6, section: 'required', hint: 'Paste toàn bộ đoạn copy cần đánh giá, bao gồm cả headline và body', example: 'Tăng doanh thu 300% với giải pháp AI quản lý bán hàng thông minh. Đăng ký dùng thử miễn phí!' },
            { id: 'type', type: 'select', label: 'Loại Copy', options: ['Headline', 'Ad', 'Email', 'Landing Page', 'Product Description'], default: 'Headline', required: true, section: 'required', hint: 'Loại copy sẽ quyết định tiêu chí đánh giá khác nhau' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Đối tượng mục tiêu', required: true, section: 'required', hint: 'Mô tả cụ thể: tuổi, nghề, nhu cầu', example: 'Chủ shop online, 25-40 tuổi, bán hàng trên Shopee/Lazada' },
            { id: 'cta', type: 'text', label: 'Mục tiêu CTA', placeholder: 'Mua hàng, đăng ký, tải app...', required: true, section: 'required', hint: 'Hành động bạn muốn người đọc thực hiện', example: 'Đăng ký dùng thử 14 ngày miễn phí' },
            { id: 'tone', type: 'select', label: 'Tone of Voice', options: ['Professional', 'Casual', 'Urgent', 'Friendly', 'Premium'], default: 'Professional', required: false, section: 'advanced', hint: 'Phong cách ngôn ngữ phù hợp với brand' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá [type] copy.

COPY:
[copy]

TARGET AUDIENCE: [audience]
CTA GOAL: [cta]
TONE: [tone]

OUTPUT FORMAT:
- Copy Score → Strengths → Issues → Rewritten Version → A/B Test Ideas

SUCCESS CRITERIA:
- Đánh giá clarity, benefits, emotional triggers
- Đánh giá CTA effectiveness
- Đề xuất cải thiện
- Viết lại phiên bản tối ưu`,
        outputExpected: ['Copy Score (/10)', 'Strengths', 'Issues', 'Rewritten Version', 'A/B Test Ideas'],
        outputTemplate: `## Copy Evaluation Output

**Score:** /10

## Strengths

## Issues

## Rewritten Version

## A/B Test Ideas`,
    },
    {
        id: 'landing_page_cro',
        name: 'Tối ưu Landing Page',
        icon: '🎯',
        description: 'Tối ưu conversion rate cho landing pages',
        category: 'marketing',
        difficulty: 'medium',
        fields: [
            { id: 'url', type: 'text', label: 'Landing Page URL', placeholder: 'https://example.com/landing', required: true, section: 'required', hint: 'URL landing page cần tối ưu', example: 'https://shopx.vn/pricing' },
            { id: 'goal', type: 'select', label: 'Mục tiêu conversion', options: ['Sign up', 'Purchase', 'Download', 'Contact', 'Free Trial'], default: 'Sign up', required: true, section: 'required', hint: 'Hành động chính bạn muốn visitor thực hiện' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Đối tượng mục tiêu', required: true, section: 'required', hint: 'ai sẽ vào landing page này?', example: 'SMB founders đang tìm project management tool' },
            { id: 'traffic', type: 'select', label: 'Traffic Source', options: ['Paid Ads', 'Organic', 'Email', 'Social', 'Mixed'], default: 'Mixed', required: false, section: 'advanced', hint: 'Nguồn traffic chính đến landing page' },
            { id: 'currentCR', type: 'text', label: 'Current Conversion Rate', placeholder: 'VD: 2.5%', required: false, section: 'advanced', hint: 'Tỷ lệ conversion hiện tại (để trống nếu chưa có)', example: '2.3% (từ 10K visitors/tháng)' },
        ],
        intentPattern: `INTENT:
Tôi muốn tối ưu conversion rate cho landing page [url].

CONVERSION GOAL: [goal]
TARGET AUDIENCE: [audience]
TRAFFIC SOURCE: [traffic]
CURRENT CR: [currentCR]

OUTPUT FORMAT:
- CRO Score → Above the Fold Analysis → Friction Points → Quick Wins → A/B Test Suggestions

SUCCESS CRITERIA:
- Đánh giá above the fold elements
- Xác định friction points
- Priority quick wins
- Đề xuất A/B tests`,
        outputExpected: ['CRO Score (/100)', 'Above the Fold Analysis', 'Friction Points', 'Quick Wins', 'A/B Test Suggestions'],
        outputTemplate: `## Landing Page CRO Output

**CRO Score:** /100

## Above the Fold Analysis

## Friction Points

## Quick Wins

## A/B Test Suggestions`,
    },
    {
        id: 'pricing_strategy',
        name: 'Review Chiến lược Giá',
        icon: '💰',
        description: 'Đánh giá và tối ưu pricing strategy',
        category: 'marketing',
        difficulty: 'medium',
        fields: [
            { id: 'product', type: 'text', label: 'Sản phẩm/Dịch vụ', placeholder: 'Mô tả offering', required: true, section: 'required', hint: 'Tên và mô tả ngắn về sản phẩm/dịch vụ', example: 'TaskFlow — SaaS quản lý dự án cho team nhỏ' },
            { id: 'currentPrice', type: 'text', label: 'Giá hiện tại', placeholder: 'Pricing structure hiện tại', required: true, section: 'required', hint: 'Mô tả các mức giá hiện tại', example: 'Free: 3 projects, Pro: $15/user/tháng, Enterprise: tùy chỉnh' },
            { id: 'model', type: 'select', label: 'Pricing Model', options: ['One-time', 'Subscription', 'Tiered', 'Freemium', 'Usage-based'], default: 'Subscription', required: true, section: 'required', hint: 'Mô hình tính giá chính đang dùng' },
            { id: 'target', type: 'select', label: 'Target Customer', options: ['B2B Enterprise', 'B2B SMB', 'B2C Premium', 'B2C Mass'], default: 'B2B SMB', required: true, section: 'required', hint: 'Phân khúc khách hàng chính' },
            { id: 'competitors', type: 'text', label: 'Giá đối thủ', placeholder: 'Pricing của competitors', required: false, section: 'advanced', hint: 'Mức giá của 2-3 đối thủ cạnh tranh trực tiếp', example: 'Asana: $10.99/user, Monday: $9/user, Trello: Free/Premium $5' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá pricing strategy cho [product].

CURRENT PRICING: [currentPrice]
MODEL: [model]
TARGET: [target]
COMPETITOR PRICES: [competitors]

OUTPUT FORMAT:
- Recommendation Summary → Pricing Tiers/Options → Assumptions/Guardrails → First Experiment → Risk/Validation Checks

SUCCESS CRITERIA:
- Concrete tiers or pricing options
- Target user per option
- Included limits/features
- Price anchors or relative bands when exact prices are not supplied
- First pricing experiment
- Risk and validation checks`,
        outputExpected: ['Recommendation Summary', 'Pricing Tiers/Options', 'Assumptions/Guardrails', 'First Experiment', 'Risk/Validation Checks'],
        outputTemplate: `## Pricing Recommendation

## 1. Recommendation Summary
- Recommended pricing model:
- Starting tiers or options:
- Target user for the first test:
- First pricing experiment:
- Assumptions to validate:

## 2. Pricing Tiers Or Options
| Tier/Option | Target User | Included Features Or Limits | Price Anchor Or Relative Band | Why It Fits | Risk |
| --- | --- | --- | --- | --- | --- |

## 3. Assumptions And Guardrails
- Supplied facts used:
- Labeled assumptions:
- Exact prices not supported by the input:
- Guardrails for discounting or exceptions:

## 4. First Experiment
| Step | Owner/Role | Action | Artifact | Success Metric | Acceptance Check |
| --- | --- | --- | --- | --- | --- |

## 5. Risk And Validation Checks
- [ ] Each tier or option has a clear target user
- [ ] Included limits or features are explicit
- [ ] Price anchors are labeled as supplied, relative, or assumed
- [ ] First experiment can be run without another strategy pass
- [ ] Risks and rollback or adjustment signals are visible`,
    },
    {
        id: 'content_quality',
        name: 'Checklist Chất lượng Nội dung',
        icon: '📄',
        description: 'Đánh giá chất lượng content với E-E-A-T',
        category: 'marketing',
        difficulty: 'medium',
        fields: [
            { id: 'content', type: 'textarea', label: 'Content URL/Text', placeholder: 'Link hoặc paste nội dung', required: true, rows: 4, section: 'required', hint: 'Dán URL bài viết hoặc paste nội dung trực tiếp', example: 'https://blog.shopx.vn/huong-dan-ban-hang-online-2026' },
            { id: 'type', type: 'select', label: 'Content Type', options: ['Blog', 'Guide', 'Landing page', 'Product page', 'How-to'], default: 'Blog', required: true, section: 'required', hint: 'Loại content sẽ quyết định tiêu chuẩn đánh giá' },
            { id: 'keyword', type: 'text', label: 'Target Keyword', placeholder: 'Từ khóa chính muốn rank', required: true, section: 'required', hint: 'Từ khóa chính mà bài viết nhắm đến', example: 'cách bán hàng online hiệu quả' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Đối tượng đọc content', required: true, section: 'required', hint: 'Ai sẽ đọc và cần nội dung này?', example: 'Người mới bắt đầu kinh doanh online, chưa có kinh nghiệm' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá chất lượng [type] content.

CONTENT:
[content]

TARGET KEYWORD: [keyword]
AUDIENCE: [audience]

OUTPUT FORMAT:
- Content Score → SEO Analysis → Readability Report → E-E-A-T Assessment → Improvement Recommendations

SUCCESS CRITERIA:
- E-E-A-T assessment
- SEO optimization check
- Readability score
- Gap analysis vs competitors`,
        outputExpected: ['Content Score (/10)', 'SEO Analysis', 'Readability Report', 'E-E-A-T Assessment', 'Improvement Recommendations'],
        outputTemplate: `## Content Quality Output

**Score:** /10

## SEO Analysis

## Readability Report

## E-E-A-T Assessment

## Improvement Recommendations`,
    },
    {
        id: 'email_campaign',
        name: 'Review Chiến dịch Email',
        icon: '📨',
        description: 'Đánh giá email marketing campaigns',
        category: 'marketing',
        difficulty: 'medium',
        fields: [
            { id: 'email', type: 'textarea', label: 'Email Content', placeholder: 'Paste full email (subject + body)', required: true, rows: 8, section: 'required', hint: 'Dán toàn bộ email bao gồm subject line và body', example: 'Subject: Đừng bỏ lỡ! Giảm 50% cho hội viên mới\n\nXin chào [Tên], Chúng tôi có ưu đãi đặc biệt dành riêng cho bạn...' },
            { id: 'type', type: 'select', label: 'Email Type', options: ['Newsletter', 'Promotional', 'Transactional', 'Nurture', 'Re-engagement'], default: 'Promotional', required: true, section: 'required', hint: 'Loại email sẽ quyết định tiêu chí đánh giá' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Segment này là ai?', required: true, section: 'required', hint: 'Mô tả segment người nhận email', example: 'Users đã đăng ký free trial nhưng chưa upgrade sau 7 ngày' },
            { id: 'goal', type: 'select', label: 'Campaign Goal', options: ['CTR', 'Sales', 'Engagement', 'Re-engagement'], default: 'CTR', required: true, section: 'required', hint: 'Mục tiêu chính của email campaign' },
        ],
        intentPattern: `INTENT:
Tôi muốn review [type] email campaign.

EMAIL:
[email]

AUDIENCE: [audience]
GOAL: [goal]

OUTPUT FORMAT:
- Email Score → Subject Line Analysis → Content Review → Deliverability Check → Rewritten Version

SUCCESS CRITERIA:
- Subject line effectiveness
- Body content quality
- CTA clarity
- Mobile-friendliness`,
        outputExpected: ['Email Score (/10)', 'Subject Line Analysis', 'Content Review', 'Deliverability Check', 'Rewritten Version'],
        outputTemplate: `## Email Campaign Output

**Score:** /10

## Subject Line Analysis

## Content Review

## Deliverability Check

## Rewritten Version`,
    },
    {
        id: 'social_ad_review',
        name: 'Review Quảng cáo MXH',
        icon: '📱',
        description: 'Tối ưu ads trên Facebook, Instagram, TikTok',
        category: 'marketing',
        difficulty: 'medium',
        fields: [
            { id: 'creative', type: 'textarea', label: 'Ad Creative', placeholder: 'Mô tả image/video hoặc link', required: true, rows: 3, section: 'required', hint: 'Mô tả hình ảnh/video quảng cáo hoặc dán link', example: 'Image: nền gradient xanh, chữ trắng "Tăng doanh thu 3X", logo góc trên phải' },
            { id: 'copy', type: 'textarea', label: 'Ad Copy', placeholder: 'Headline + Primary text + CTA', required: true, rows: 4, section: 'required', hint: 'Bao gồm headline, primary text, và nút CTA', example: 'Headline: Quản lý team hiệu quả hơn 3X\nPrimary: Gần 10,000 teams đã dùng TaskFlow...\nCTA: Dùng thử miễn phí' },
            { id: 'platform', type: 'select', label: 'Platform', options: ['Facebook', 'Instagram', 'TikTok', 'LinkedIn', 'YouTube'], default: 'Facebook', required: true, section: 'required', hint: 'Mỗi platform có best practices và format riêng' },
            { id: 'objective', type: 'select', label: 'Campaign Objective', options: ['Traffic', 'Conversions', 'Leads', 'Awareness', 'Engagement'], default: 'Conversions', required: true, section: 'required', hint: 'Mục tiêu chính của chiến dịch quảng cáo' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Demographics, interests, behaviors', required: true, section: 'required', hint: 'Mô tả đối tượng mục tiêu chi tiết', example: 'Nam/Nữ 25-45, quản lý/founders, quan tâm productivity & project management' },
        ],
        intentPattern: `INTENT:
Tôi muốn review [platform] ad cho mục tiêu [objective].

CREATIVE:
[creative]

AD COPY:
[copy]

AUDIENCE: [audience]

OUTPUT FORMAT:
- Ad Score → Creative Analysis → Copy Review → Platform Optimization → A/B Test Ideas → Rewritten Ad

SUCCESS CRITERIA:
- Creative effectiveness (thumb-stopping)
- Copy quality (hook, benefits, CTA)
- Platform optimization
- Predicted performance`,
        outputExpected: ['Ad Score (/10)', 'Creative Analysis', 'Copy Review', 'Platform Optimization', 'A/B Test Ideas', 'Rewritten Ad'],
        outputTemplate: `## Social Ad Review Output

**Score:** /10

## Creative Analysis

## Copy Review

## Platform Optimization

## A/B Test Ideas

## Rewritten Ad`,
    },
    {
        id: 'brand_voice',
        name: 'Đồng bộ Giọng điệu Thương hiệu',
        icon: '🎙️',
        description: 'Đảm bảo brand voice nhất quán',
        category: 'marketing',
        difficulty: 'medium',
        fields: [
            { id: 'brand', type: 'text', label: 'Brand Name', placeholder: 'Tên thương hiệu', required: true, section: 'required', hint: 'Tên thương hiệu cần đánh giá voice consistency', example: 'TaskFlow' },
            { id: 'industry', type: 'text', label: 'Industry', placeholder: 'Ngành nghề', required: true, section: 'required', hint: 'Ngành kinh doanh của thương hiệu', example: 'SaaS / Productivity Tools' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Customer persona chính', required: true, section: 'required', hint: 'Khách hàng mục tiêu chính của brand', example: 'SMB founders và team leaders, 28-45 tuổi' },
            { id: 'samples', type: 'textarea', label: 'Sample Content', placeholder: '3-5 samples từ các channels khác nhau', required: true, rows: 6, section: 'required', hint: 'Dán 3-5 đoạn content từ các kênh khác nhau (web, email, social)', example: 'Website: "Streamline your workflow..."\nEmail: "Hey team! Check out..."\nSocial: "🚀 Big news!..."' },
            { id: 'values', type: 'text', label: 'Brand Values', placeholder: 'Core values của brand', required: false, section: 'advanced', hint: 'Giá trị cốt lõi của thương hiệu', example: 'Simple, Reliable, Human-friendly' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá brand voice consistency cho [brand].

INDUSTRY: [industry]
TARGET AUDIENCE: [audience]
BRAND VALUES: [values]

SAMPLE CONTENT:
[samples]

OUTPUT FORMAT:
- Voice Audit → Consistency Score → Voice Attributes → Tone Matrix → Language Guidelines

SUCCESS CRITERIA:
- Voice attributes assessment
- Cross-channel consistency
- Tone appropriateness
- Improvement recommendations`,
        outputExpected: ['Voice Audit', 'Consistency Score (/10)', 'Voice Attributes', 'Tone Matrix', 'Language Guidelines'],
        outputTemplate: `## Brand Voice Output

## Voice Audit

**Consistency Score:** /10

## Voice Attributes

## Tone Matrix

## Language Guidelines`,
    },
];
