import { Template } from '@/types';

export const productTemplates: Template[] = [
    {
        id: 'product_design_wizard',
        name: '🎨 Thiết kế Sản phẩm',
        icon: '🎨',
        description: 'Multi-step wizard tạo Product Design Spec với governed packet và live path để đối soát',
        category: 'product',
        difficulty: 'medium',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Product Design Spec', 'User Personas', 'User Flows', 'Design Brief'],
    },
    {
        id: 'accessibility_audit',
        name: 'Kiểm tra Accessibility',
        icon: '♿',
        description: 'Kiểm tra WCAG compliance',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'url', type: 'text', label: 'Page URL', placeholder: 'https://example.com/page', required: true, section: 'required', hint: 'URL trang cần kiểm tra accessibility', example: 'https://shopx.vn/checkout' },
            { id: 'level', type: 'select', label: 'WCAG Level', options: ['A', 'AA', 'AAA'], default: 'AA', required: true, section: 'required', hint: 'AA là mức tiêu chuẩn phổ biến nhất, AAA là cao nhất' },
            { id: 'audience', type: 'text', label: 'Target Users', placeholder: 'Đối tượng sử dụng có disability nào?', required: false, section: 'advanced', hint: 'Loại disability cần ưu tiên hỗ trợ', example: 'Người khiếm thị sử dụng screen reader, người cao tuổi' },
            { id: 'issues', type: 'textarea', label: 'Known Issues', placeholder: 'Các issues đã biết', required: false, rows: 3, section: 'advanced', hint: 'Liệt kê issues accessibility đã biết (nếu có)', example: 'Form checkout không navigate được bằng keyboard, contrast thấp ở footer' },
        ],
        intentPattern: `INTENT:
Tôi muốn audit accessibility cho page [url].

TARGET WCAG LEVEL: [level]
TARGET USERS: [audience]
KNOWN ISSUES: [issues]

OUTPUT FORMAT:
- WCAG Compliance Score → Critical Issues → Recommended Fixes → Testing Checklist

SUCCESS CRITERIA:
- Visual accessibility check
- Keyboard navigation
- Screen reader compatibility
- Color contrast analysis`,
        outputExpected: ['WCAG Compliance Score', 'Critical Issues', 'Recommended Fixes', 'Testing Checklist'],
        outputTemplate: `## Accessibility Audit Output

**WCAG Compliance Score:**

## Critical Issues

## Recommended Fixes

## Testing Checklist`,
    },
    {
        id: 'user_flow_analysis',
        name: 'Phân tích User Flow',
        icon: '🔄',
        description: 'Phân tích và tối ưu user journeys',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'flow', type: 'textarea', label: 'User Flow', placeholder: 'Mô tả các steps từ entry đến goal', required: true, rows: 6, section: 'required', hint: 'Mô tả từng bước user đi qua, từ lúc vào trang đến khi hoàn thành', example: '1. Landing page → 2. Click "Xem giá" → 3. Pricing page → 4. Chọn gói → 5. Form đăng ký → 6. Thanh toán → 7. Confirmation' },
            { id: 'goal', type: 'text', label: 'Conversion Goal', placeholder: 'VD: Complete purchase', required: true, section: 'required', hint: 'Hành động cuối cùng mà user cần thực hiện', example: 'Hoàn thành thanh toán và nhận mã đơn hàng' },
            { id: 'dropoff', type: 'textarea', label: 'Drop-off Points', placeholder: 'Các điểm users rời khỏi flow', required: false, rows: 3, section: 'advanced', hint: 'Các bước mà users thường bỏ dở', example: 'Bước 5 (form đăng ký): 45% drop-off\nBước 6 (thanh toán): 20% drop-off' },
            { id: 'metrics', type: 'text', label: 'Current Metrics', placeholder: 'Conversion rates at each step', required: false, section: 'advanced', hint: 'Tỷ lệ conversion tại mỗi bước (nếu có)', example: 'Overall CR: 1.8%, Step 3→4: 65%, Step 5→6: 55%' },
        ],
        intentPattern: `INTENT:
Tôi muốn phân tích user flow.

FLOW DESCRIPTION:
[flow]

CONVERSION GOAL: [goal]
DROP-OFF POINTS: [dropoff]
CURRENT METRICS: [metrics]

OUTPUT FORMAT:
- Flow Diagram → Friction Analysis → Drop-off Causes → Optimization Roadmap

SUCCESS CRITERIA:
- Friction point identification
- Drop-off analysis
- Optimization recommendations
- Quick wins vs long-term fixes`,
        outputExpected: ['Flow Diagram', 'Friction Analysis', 'Drop-off Causes', 'Optimization Roadmap'],
        outputTemplate: `## User Flow Analysis Output

## 1. Flow Diagram (text)

## 2. Friction Analysis

## 3. Drop-off Causes

## 4. Optimization Roadmap`,
    },
    {
        id: 'ux_heuristic_evaluation',
        name: 'Đánh giá UX Heuristic',
        icon: '📋',
        description: 'Đánh giá UX theo Nielsen\'s 10 Heuristics',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'product', type: 'text', label: 'Product/Feature', placeholder: 'Tên sản phẩm hoặc feature', required: true, section: 'required', hint: 'Tên sản phẩm hoặc feature cần đánh giá UX', example: 'TaskFlow — Dashboard quản lý dự án' },
            { id: 'description', type: 'textarea', label: 'Description', placeholder: 'Mô tả product/feature', required: true, rows: 4, section: 'required', hint: 'Mô tả chức năng chính và cách user tương tác', example: 'Dashboard hiển thị tất cả projects, tasks, và deadlines. Có drag-and-drop, filter, và search.' },
            { id: 'url', type: 'text', label: 'URL (nếu có)', placeholder: 'Link đến product', required: false, section: 'advanced', hint: 'URL để AI có thể tham khảo giao diện' },
            { id: 'focus', type: 'text', label: 'Focus Areas', placeholder: 'Các areas cần focus', required: false, section: 'advanced', hint: 'Tập trung vào những heuristic nào?', example: 'Error prevention, User control, Consistency' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá UX heuristics cho [product].

DESCRIPTION: [description]
URL: [url]
FOCUS AREAS: [focus]

OUTPUT FORMAT:
- Heuristic Scores → Issue Severity Matrix → Top Issues → Recommendations

SUCCESS CRITERIA:
- Đánh giá theo Nielsen's 10 Heuristics
- Severity rating cho issues
- Priority recommendations
- Before/After examples`,
        outputExpected: ['Heuristic Scores', 'Issue Severity Matrix', 'Top Issues', 'Recommendations'],
        outputTemplate: `## UX Heuristic Evaluation Output

## 1. Heuristic Scores
| Heuristic | Score (/5) | Status |
| --- | --- | --- |

## 2. Issue Severity Matrix

## 3. Top Issues

## 4. Recommendations`,
    },
    {
        id: 'feature_prioritization',
        name: 'Ưu tiên Tính năng',
        icon: '⚖️',
        description: 'RICE/ICE framework cho feature prioritization',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'features', type: 'textarea', label: 'Feature List', placeholder: 'Danh sách features cần prioritize', required: true, rows: 6, section: 'required', hint: 'Mỗi feature 1 dòng, kèm mô tả ngắn', example: '1. Real-time collaboration\n2. Mobile app\n3. Gantt chart view\n4. Custom fields\n5. Automations' },
            { id: 'goal', type: 'text', label: 'Product Goal', placeholder: 'Mục tiêu product hiện tại', required: true, section: 'required', hint: 'Mục tiêu chính của product trong quý này', example: 'Tăng DAU từ 5K lên 15K và giảm churn xuống dưới 5%' },
            { id: 'constraints', type: 'text', label: 'Constraints', placeholder: 'Budget, timeline, resources...', required: false, section: 'advanced', hint: 'Giới hạn về nguồn lực và thời gian', example: '2 engineers, 1 designer, deadline Q2 2026' },
            { id: 'framework', type: 'select', label: 'Framework', options: ['RICE', 'ICE', 'MoSCoW', 'Kano'], default: 'RICE', required: false, section: 'advanced', hint: 'RICE = Reach, Impact, Confidence, Effort. ICE = Impact, Confidence, Ease' },
        ],
        intentPattern: `INTENT:
Tôi muốn prioritize features bằng [framework] framework.

FEATURES:
[features]

PRODUCT GOAL: [goal]
CONSTRAINTS: [constraints]

OUTPUT FORMAT:
- MVP Scope → Why This Scope → Supporting Scoring Matrix → Implementation/Validation Steps → Risk And Deferral Checks

SUCCESS CRITERIA:
- Prioritized list includes do-now / do-next / defer groups
- Every top feature has a first implementation or validation step
- MVP scope is explicit enough for a non-technical operator to hand off
- Scoring supports the scope decision instead of replacing it
- Acceptance checks are observable`,
        outputExpected: ['MVP Scope', 'Why This Scope', 'Supporting Scoring Matrix', 'Implementation/Validation Steps', 'Risk And Deferral Checks'],
        outputTemplate: `## MVP Scope And Prioritization Decision

## 1. Recommended Scope First
- Do now / MVP:
- Do next:
- Defer:
- Explicit non-goals:
- First validation or build step:
- Owner/role:
- Acceptance check:

## 2. Why This Scope
- Product/operator goal:
- Constraints:
- Main tradeoff:
- Assumptions to confirm:

## 3. Supporting Scoring Matrix
| Feature | User Problem Solved | Reach | Impact | Confidence | Effort | Score | Rank |
| --- | --- | --- | --- | --- | --- | --- | --- |

## 4. Implementation Or Validation Steps
| Step | Owner/Role | Action | Artifact | Success Metric | Acceptance Check |
| --- | --- | --- | --- | --- | --- |

## 5. Risk And Deferral Checks
- [ ] Owner can explain why each top item was chosen
- [ ] Deferred items have a reason and revisit trigger
- [ ] First implementation or validation step is clear
- [ ] Operator can verify completion without developer interpretation`,
    },
    {
        id: 'user_persona',
        name: 'Xây dựng User Persona',
        icon: '👤',
        description: 'Tạo user personas dựa trên data',
        category: 'product',
        difficulty: 'easy',
        fields: [
            { id: 'product', type: 'text', label: 'Product/Service', placeholder: 'Tên sản phẩm/dịch vụ', required: true, section: 'required', hint: 'Sản phẩm/dịch vụ cần tạo persona', example: 'TaskFlow — ứng dụng quản lý dự án' },
            { id: 'data', type: 'textarea', label: 'User Data', placeholder: 'Demographics, behaviors, interviews...', required: true, rows: 6, section: 'required', hint: 'Dữ liệu về users: từ survey, analytics, phỏng vấn...', example: '70% users là PM/team lead, 60% dùng mobile, pain point chính: track deadlines và assign tasks' },
            { id: 'segments', type: 'text', label: 'User Segments', placeholder: 'Các segments đã biết', required: false, section: 'advanced', hint: 'Các nhóm users đã xác định (nếu có)', example: 'Freelancers, Small teams (2-10), Mid-size teams (10-50)' },
            { id: 'goals', type: 'text', label: 'Business Goals', placeholder: 'Mục tiêu kinh doanh', required: false, section: 'advanced', hint: 'Mục tiêu kinh doanh liên quan đến personas', example: 'Tăng adoption từ small teams, giảm churn segment freelancer' },
        ],
        intentPattern: `INTENT:
Tôi muốn tạo user personas cho [product].

USER DATA:
[data]

SEGMENTS: [segments]
BUSINESS GOALS: [goals]

OUTPUT FORMAT:
- Persona Profiles and Decision Signals → Persona-Linked Actions → First Experiments → Persona Usability Checks

SUCCESS CRITERIA:
- 2-4 distinct personas
- Each persona has trigger, objection, decision criteria, and success signal
- Each persona maps to product, marketing/support, and onboarding or activation action
- Each persona has a first experiment
- Acceptance checks prove whether the persona is usable`,
        outputExpected: ['Persona Profiles and Decision Signals', 'Persona-Linked Actions', 'First Experiments', 'Persona Usability Checks'],
        outputTemplate: `# Persona-To-Action Packet

## 1. Segments And Assumptions
- Source data used:
- Assumptions:
- Segment boundaries:

## 2. Persona Profiles And Decision Signals
| Persona | Context | Job To Be Done | Trigger | Objection | Decision Criteria | Success Signal |
| --- | --- | --- | --- | --- | --- | --- |

## 3. Persona-Linked Actions
| Persona | Product Action | Marketing/Support Action | Onboarding Or Activation Action | Owner/Role | Acceptance Check |
| --- | --- | --- | --- | --- | --- |

## 4. First Experiments
| Persona | Experiment | Hypothesis | Success Metric | Timebox | Decision Rule |
| --- | --- | --- | --- | --- | --- |

## 5. Persona Usability Checks
- [ ] Every persona has a trigger, objection, decision criteria, and success signal
- [ ] Every persona maps to at least one product action and one marketing/support action
- [ ] Every persona has a first experiment and measurable acceptance check
- [ ] Unsupported demographic or behavioral claims are labeled as assumptions`,
    },
    {
        id: 'error_handling_ux',
        name: 'UX Xử lý Lỗi',
        icon: '🛑',
        description: 'Cải thiện cách handle errors',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'errors', type: 'textarea', label: 'Current Error Messages', placeholder: 'Paste các error messages hiện tại', required: true, rows: 6, section: 'required', hint: 'Dán các error messages người dùng đang thấy', example: '"Error 500: Internal Server Error"\n"Something went wrong. Try again later."\n"Invalid input"' },
            { id: 'context', type: 'text', label: 'Error Context', placeholder: 'Form, checkout, login, etc.', required: true, section: 'required', hint: 'Màn hình/chức năng nơi error xuất hiện', example: 'Form checkout và trang tạo tài khoản' },
            { id: 'audience', type: 'text', label: 'User Type', placeholder: 'Technical users hay end users?', required: false, section: 'advanced', hint: 'Mức độ kỹ thuật của người dùng', example: 'End users không có kiến thức kỹ thuật' },
            { id: 'tone', type: 'select', label: 'Brand Tone', options: ['Friendly', 'Professional', 'Technical', 'Playful'], default: 'Friendly', required: false, section: 'advanced', hint: 'Phong cách ngôn ngữ phù hợp với brand' },
        ],
        intentPattern: `INTENT:
Tôi muốn cải thiện error handling UX cho context [context].

CURRENT ERRORS:
[errors]

USER TYPE: [audience]
BRAND TONE: [tone]

OUTPUT FORMAT:
- Error Analysis → Rewritten Messages → UX Improvements → Best Practices

SUCCESS CRITERIA:
- Error message clarity
- User guidance
- Recovery options
- Consistent tone`,
        outputExpected: ['Error Analysis', 'Rewritten Messages', 'UX Improvements', 'Best Practices'],
        outputTemplate: `## Error Handling UX Output

## 1. Error Analysis

## 2. Rewritten Messages
| Original | Improved |
| --- | --- |

## 3. UX Improvements

## 4. Best Practices`,
    },
    {
        id: 'onboarding_review',
        name: 'Review Onboarding',
        icon: '🎓',
        description: 'Tối ưu first-time user experience',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'product', type: 'text', label: 'Product', placeholder: 'Tên sản phẩm', required: true, section: 'required', hint: 'Tên sản phẩm cần đánh giá onboarding', example: 'TaskFlow' },
            { id: 'flow', type: 'textarea', label: 'Current Onboarding Flow', placeholder: 'Mô tả các steps hiện tại', required: true, rows: 6, section: 'required', hint: 'Liệt kê từng bước onboarding từ lúc đăng ký đến khi user thấy giá trị', example: '1. Sign up form (email + password)\n2. Email verification\n3. Chọn workspace name\n4. Invite team members\n5. Tạo project đầu tiên\n6. Tour hướng dẫn' },
            { id: 'ttv', type: 'text', label: 'Time to Value', placeholder: 'Hiện tại bao lâu để user thấy value?', required: false, section: 'advanced', hint: 'Thời gian trung bình từ đăng ký đến "aha moment"', example: '~15 phút, aha moment = tạo task đầu tiên và assign cho team' },
            { id: 'dropoff', type: 'text', label: 'Drop-off Rate', placeholder: '% users drop-off during onboarding', required: false, section: 'advanced', hint: 'Tỷ lệ users bỏ cuộc giữa chừng onboarding', example: '40% drop-off ở bước 4 (invite team)' },
        ],
        intentPattern: `INTENT:
Tôi muốn review onboarding experience cho [product].

CURRENT FLOW:
[flow]

TIME TO VALUE: [ttv]
DROP-OFF RATE: [dropoff]

OUTPUT FORMAT:
- Onboarding Assessment → Friction Points → Optimization Recommendations → Metrics to Track

SUCCESS CRITERIA:
- Identify friction points
- Reduce time to value
- Progressive disclosure
- Personalization opportunities`,
        outputExpected: ['Onboarding Assessment', 'Friction Points', 'Optimization Recommendations', 'Metrics to Track'],
        outputTemplate: `## Onboarding Review Output

## 1. Onboarding Assessment

## 2. Friction Points

## 3. Optimization Recommendations

## 4. Metrics to Track`,
    },
    {
        id: 'web_ux_redesign_system',
        name: 'Hệ thống UX Web',
        icon: '🧭',
        description: 'Biến brief giao diện thành packet UX/UI có review gate rõ ràng để non-coder duyệt hướng UX an toàn trước khi builder đụng vào phần build.',
        category: 'product',
        difficulty: 'advanced',
        fields: [
            { id: 'projectSurface', type: 'text', label: 'Website / sản phẩm này là gì?', placeholder: 'Mô tả ngắn gọn website hoặc app cần làm', required: true, section: 'required', hint: 'Không cần nói framework. Chỉ cần nói đây là loại sản phẩm gì.', example: 'AI operations dashboard cho team nội bộ' },
            { id: 'users', type: 'text', label: 'Ai sẽ dùng nó?', placeholder: 'Nhóm người dùng chính', required: true, section: 'required', hint: 'Liệt kê người dùng hoặc vai trò chính.', example: 'Ops manager, analyst, admin' },
            { id: 'coreFlows', type: 'textarea', label: 'Người dùng cần làm gì trên web?', placeholder: '3-5 việc quan trọng nhất mà người dùng phải làm được', required: true, rows: 4, section: 'required', hint: 'Mô tả bằng ngôn ngữ công việc hằng ngày, không cần thuật ngữ UX.', example: 'Search knowledge\nRun workflow\nReview result\nManage settings' },
            { id: 'pagesModals', type: 'textarea', label: 'Những màn hình / popup cần có', placeholder: 'Liệt kê page, modal, drawer, panel cần xây', required: true, rows: 4, section: 'required', hint: 'Chỉ cần liệt kê những chỗ bạn muốn agent xây hoặc redesign.', example: 'Home, Skills, Search, Docs, Settings modal' },
            { id: 'mustPreserve', type: 'textarea', label: 'Những gì tuyệt đối không được đổi', placeholder: 'Logic, dữ liệu, route, auth... cần giữ nguyên', required: true, rows: 4, section: 'required', hint: 'Đây là lớp bảo vệ để agent chỉ đổi UX/UI, không phá logic ẩn bên dưới.', example: 'Routes, auth, API payloads, Zustand store, provider execution flow' },
            { id: 'visualDirection', type: 'text', label: 'Bạn muốn giao diện có cảm giác như thế nào?', placeholder: 'Mô tả phong cách mong muốn', required: true, section: 'required', hint: 'Nói về cảm giác và level giao diện, ví dụ: premium, bold, tối giản, data-heavy.', example: 'Dark-primary, premium, structured, bold headings, data-aware' },
            { id: 'contentDensity', type: 'select', label: 'Lượng thông tin trên màn hình', options: ['Light', 'Balanced', 'Balanced to Dense', 'Dense'], default: 'Balanced', required: false, section: 'advanced', hint: 'Chọn mức thoáng hay dày đặc của thông tin.' },
            { id: 'motionBudget', type: 'select', label: 'Mức chuyển động / animation', options: ['Minimal', 'Intentional', 'Rich'], default: 'Intentional', required: false, section: 'advanced', hint: 'Chỉ chọn mức cảm giác mong muốn, agent sẽ tự chuyển thành rule cụ thể.' },
            { id: 'themeStrategy', type: 'select', label: 'Ưu tiên dark hay light?', options: ['Dark-primary + light-supporting', 'Light-primary + dark-supporting', 'Dual parity'], default: 'Dark-primary + light-supporting', required: false, section: 'advanced', hint: 'Chỉ cần nói ưu tiên giao diện, không cần hiểu hệ theme bên dưới.' },
            { id: 'references', type: 'textarea', label: 'Ghi chú / ví dụ tham khảo', placeholder: 'Link, file, hoặc ghi chú style nếu có', required: false, rows: 3, section: 'advanced', hint: 'Nếu có app hoặc page bạn thích, chỉ cần mô tả hoặc dán link.', example: 'Use CVF redesign cues: stat strip, pill filters, structured cards, docs split-pane' },
        ],
        intentPattern: `INTENT:
Tôi muốn biến brief giao diện này thành một packet handoff để agent khác có thể xây web.

PROJECT / SURFACE:
[projectSurface]

USERS / ROLES:
[users]

CORE FLOWS:
[coreFlows]

PAGES / MODALS:
[pagesModals]

MUST PRESERVE:
[mustPreserve]

VISUAL DIRECTION:
[visualDirection]

CONTENT DENSITY: [contentDensity]
MOTION BUDGET: [motionBudget]
THEME STRATEGY: [themeStrategy]
REFERENCES / NOTES: [references]

OUTPUT FORMAT:
- Experience North Star → Visual DNA → Layout & Navigation → Component Language → Surface Blueprint → Implementation Guardrails → Review Gate

SUCCESS CRITERIA:
- The end user does not need to choose frameworks or hidden technical patterns
- Extract reusable design DNA instead of one-off mockup notes
- Apply CVF Redesign DNA from cvf_web_ux_redesign_system: dark-primary command workspace, layered panels, stat strips, pill filters, compact operational cards, restrained motion, and clear state design
- Preserve logic/runtime boundaries
- Define layout, component, state, and QA rules — label this section "QA Rules" with pre-build approval and post-build validation checklists
- Produce an agent-ready web build handoff packet
- Include an explicit review gate so non-coder approval happens before builder-side runtime changes — label this section "Review Gate"`,
        outputExpected: ['Product Goal & User Promise', 'UX Style DNA', 'Page / Modal Blueprint', 'Component & State Rules', 'Responsive / Accessibility Rules', 'Agent Build Guardrails', 'Review Gate & Acceptance Checklist'],
        outputTemplate: `## 1. Experience North Star
- Product promise
- User feeling
- Operational posture

## 2. Visual DNA
- Typography
- Color roles
- Surface hierarchy
- Accent rules
- Anti-patterns

## 3. Layout & Navigation System
- Shell pattern
- Sidebar / topbar rules
- Section rhythm

## 4. Component Language
- Buttons
- Inputs
- Filters
- Cards
- Tables / charts
- Modals / drawers
- Empty / loading / error states

## 5. Surface Blueprint
- Page-by-page hierarchy
- Primary CTA / secondary CTA
- Mobile adaptation

## 6. Implementation Guardrails
- What must stay unchanged
- What can be restyled
- Tokenization plan
- QA checklist

## 7. Review Gate & Acceptance Checklist
- What the non-coder should confirm
- What requires explicit builder approval
- What would count as overreach`,
        sampleOutput: `# Web Build Handoff Packet

## 1. Product Goal & User Promise
- Build a high-trust AI operations dashboard for internal teams.
- The UI should feel premium, structured, and calm under pressure.

## 2. UX Style DNA
- Dark-primary shell, layered panels, clear border separation
- Editorial headings + compact operational body text
- Indigo reserved for active state and key actions
- Avoid generic AI gradients and random colorful cards

## 3. Page / Modal Blueprint
- Home: stat strip, key actions, recent workflows
- Search: large query bar, quick tags, result list
- Docs: split-pane navigation + readable content column
- Settings modal: grouped controls, clear save state

## 4. Component & State Rules
- Cards: strong hierarchy, no decorative clutter
- Filters: pill controls with clear active state
- Empty state: explain what to do next
- Loading: skeleton or progress feedback, never blank wait
- Error: plain-language recovery guidance

## 5. Responsive / Accessibility Rules
- Mobile: no horizontal scroll, stack cards earlier
- Keyboard focus must stay visible
- Touch targets >= 44px
- Dark is hero, light still must be readable and complete

## 6. Agent Build Guardrails
- Preserve routes, auth, APIs, existing state/store contracts
- Restyle shell/components only unless explicitly approved
- Agent chooses technical implementation details internally
- Final QA: desktop + mobile + loading/empty/error states

## 7. Review Gate & Acceptance Checklist
- Non-coder approves page hierarchy, visual direction, and preserved constraints before build starts
- Any route/auth/API/store change requires explicit separate approval
- Reject the build if the proposal changes protected runtime behavior instead of UX/UI only`,
    },
    {
        id: 'web_build_handoff',
        name: 'Bàn giao Web cho Agent',
        icon: '📦',
        description: 'Template cực ngắn cho non-coder: chỉ mô tả website bằng ngôn ngữ thường ngày, CVF sẽ tự đóng gói thành packet build cho agent',
        category: 'product',
        difficulty: 'easy',
        fields: [
            { id: 'websiteGoal', type: 'text', label: 'Website này để làm gì?', placeholder: 'Mục tiêu chính của website', required: true, section: 'required', hint: 'Viết theo ngôn ngữ kinh doanh hoặc công việc, không cần từ kỹ thuật.', example: 'Giúp khách hàng đăng ký tư vấn và xem dịch vụ nhanh hơn' },
            { id: 'audience', type: 'text', label: 'Ai sẽ dùng website?', placeholder: 'Người dùng chính', required: true, section: 'required', hint: 'Nói rõ nhóm người dùng chính hoặc vai trò của họ.', example: 'Chủ doanh nghiệp nhỏ đang tìm giải pháp AI automation' },
            { id: 'mustDo', type: 'textarea', label: 'Người dùng phải làm được những việc nào?', placeholder: '3-5 việc quan trọng nhất', required: true, rows: 4, section: 'required', hint: 'Chỉ mô tả việc người dùng muốn làm trên web.', example: 'Xem dịch vụ\nSo sánh gói\nĐăng ký tư vấn\nĐể lại thông tin liên hệ' },
            { id: 'screens', type: 'textarea', label: 'Cần những trang / popup nào?', placeholder: 'Liệt kê page hoặc modal cần có', required: true, rows: 4, section: 'required', hint: 'Liệt kê những màn hình bạn mong agent tạo ra.', example: 'Home, Services, Pricing, Contact form modal, Thank-you page' },
            { id: 'mustPreserve', type: 'textarea', label: 'Những gì phải giữ nguyên', placeholder: 'Logic, dữ liệu, tích hợp, auth... nếu có', required: true, rows: 3, section: 'required', hint: 'Nếu có backend hay logic sẵn, hãy nói phần nào không được đụng vào.', example: 'Webhook form sang CRM, routes hiện tại, auth admin, API submit lead' },
            { id: 'lookAndFeel', type: 'text', label: 'Bạn muốn giao diện mang cảm giác gì?', placeholder: 'Phong cách mong muốn', required: true, section: 'required', hint: 'Mô tả cảm giác tổng thể của giao diện.', example: 'Tin cậy, sáng rõ, hiện đại, dễ đọc trên mobile' },
            { id: 'references', type: 'textarea', label: 'Ví dụ / ghi chú thêm', placeholder: 'Link tham khảo hoặc ghi chú ngắn', required: false, rows: 3, section: 'advanced', hint: 'Nếu có site bạn thích hoặc điều cần tránh, hãy ghi vào đây.', example: 'Thích kiểu section rõ, headline mạnh, CTA nổi; tránh kiểu quá nhiều hiệu ứng' },
        ],
        intentPattern: `INTENT:
Tôi là non-coder và muốn CVF biến brief này thành packet bàn giao để agent khác xây website.

WEBSITE GOAL:
[websiteGoal]

TARGET USERS:
[audience]

USERS MUST BE ABLE TO:
[mustDo]

REQUIRED PAGES / MODALS:
[screens]

MUST PRESERVE:
[mustPreserve]

LOOK AND FEEL:
[lookAndFeel]

REFERENCES / NOTES:
[references]

OUTPUT REQUIREMENTS:
- Ask only for plain-language product intent, not hidden technical choices
- Translate the brief into a clear agent-ready web build packet
- Use the CVF Web Redesign DNA automatically: professional command workspace, dark-primary layered shell by default, strong page hierarchy, KPI/stat strips where useful, pill filters, compact cards/tables, meaningful empty/loading/error states, and restrained hover/motion
- Preserve existing logic, integrations, data contracts, and protected flows
- Give page structure, UX priorities, and acceptance checklist
- Keep the result simple enough for a non-coder to review before handoff

OUTPUT FORMAT:
- Website Goal → Target Users → Required Pages and Flows → CVF Web Redesign DNA → UX / Visual Direction → Protected Constraints → Agent Build Instructions → Acceptance Checklist

SUCCESS CRITERIA:
- Non-coder can read and approve the packet without technical knowledge
- Agent has all information needed to build without asking the user for framework or stack choices`,
        outputExpected: ['Website Goal & Audience', 'Page / Flow List', 'UX Direction', 'Protected Constraints', 'Agent Build Packet', 'Acceptance Checklist'],
        outputTemplate: `# Web Build Handoff Packet

## 1. Website Goal
- Business goal
- Primary user promise

## 2. Target Users
- Main audiences
- What they need to accomplish

## 3. Required Pages and Flows
- Pages
- Modals / forms
- Primary user journey

## 4. CVF Web Redesign DNA
- Experience tone and shell pattern
- Color, typography, component, and motion rules
- Anti-patterns to avoid

## 5. UX / Visual Direction
- Tone and feel
- Content density
- CTA hierarchy
- Mobile behavior

## 6. Protected Constraints
- Logic to preserve
- APIs / integrations to preserve
- Data / auth / routes that must not change

## 7. Agent Build Instructions
- What to build
- What can be redesigned
- What must remain unchanged

## 8. Acceptance Checklist
- Desktop + mobile
- Empty / loading / error states
- Clear CTA and readable content
- Accessibility basics`,
        sampleOutput: `# Web Build Handoff Packet

## 1. Website Goal
- Help small-business owners understand the service quickly and book a consultation.
- The site should feel trustworthy, fast, and easy to act on.

## 2. Target Users
- Founders and operations leads with limited technical background.
- They need to understand the offer, compare packages, and submit contact details.

## 3. Required Pages and Flows
- Home, Services, Pricing, FAQ, Contact modal, Thank-you page
- Main flow: land on Home -> review services -> compare pricing -> submit consultation form

## 4. CVF Web Redesign DNA
- Use the CVF-style command workspace language where appropriate: layered surfaces, crisp section hierarchy, compact cards, pill filters, and restrained motion.
- Keep the interface premium and operational, not decorative.

## 5. UX / Visual Direction
- Clean, bright, editorial layout with strong section separation
- CTA buttons should stand out without looking flashy
- Mobile should prioritize scanability and short decision paths

## 6. Protected Constraints
- Keep current lead form API, CRM webhook, admin auth, and route structure
- Do not change payload fields or backend validation logic

## 7. Agent Build Instructions
- Redesign presentation layer and information flow
- Keep business logic and integrations intact
- Choose internal implementation details without asking the end user to pick frameworks

## 8. Acceptance Checklist
- Works well on desktop and mobile
- Includes loading, empty, and error feedback
- Form is easy to complete
- Copy is readable for non-technical users`,
    },
];
