<#
.SYNOPSIS
Hermetic-first Party B Group 4 lookup-response initializer and appender.
.DESCRIPTION
Default invocation runs non-mutating tests. Real writes are principal-bound,
guarded, pre-hardened copy-on-write transactions. Peer and crash modes are
test-only and accept only disposable paths below the system temp root.
#>
[CmdletBinding(DefaultParameterSetName='SelfTest')]
param(
 [Parameter(ParameterSetName='SelfTest')][switch]$SelfTest,
 [Parameter(ParameterSetName='Initialize',Mandatory=$true)][switch]$InitializeResponseLog,
 [Parameter(ParameterSetName='Append',Mandatory=$true)][switch]$ExecuteLookupAppend,
 [Parameter(ParameterSetName='Append',Mandatory=$true)][string]$RequestJsonPath,
 [Parameter(ParameterSetName='Initialize',Mandatory=$true)][Parameter(ParameterSetName='Append',Mandatory=$true)][string]$RepositoryRoot,
 [Parameter(ParameterSetName='Initialize',Mandatory=$true)][Parameter(ParameterSetName='Append',Mandatory=$true)][string]$Confirmation,
 [Parameter(ParameterSetName='Initialize',Mandatory=$true)][Parameter(ParameterSetName='Append',Mandatory=$true)][string]$PythonExecutablePath,
 [Parameter(ParameterSetName='Peer',Mandatory=$true)][switch]$PeerMode,
 [Parameter(ParameterSetName='Peer',Mandatory=$true)][string]$PeerRunId,
 [Parameter(ParameterSetName='Peer',Mandatory=$true)][string]$PeerFixtureRoot,
 [Parameter(ParameterSetName='Peer')][switch]$PeerExpectAppend,
 [Parameter(ParameterSetName='Crash',Mandatory=$true)][switch]$CrashMode,
 [Parameter(ParameterSetName='Crash',Mandatory=$true)][string]$CrashRunId,
 [Parameter(ParameterSetName='Crash',Mandatory=$true)][string]$CrashFixtureRoot,
 [Parameter(ParameterSetName='Crash',Mandatory=$true)][ValidateSet('AfterAcquireBeforeMutation','AfterTempFlush','BeforeReplace')][string]$CrashPoint
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:PartyBAccount='LAM-RUBY\cvf-g1-party-b';$script:PartyBSid='S-1-5-21-1644666849-912006174-747199667-1009';$script:PartyCSid='S-1-5-21-1644666849-912006174-747199667-1010';$script:LocalSid='S-1-5-21-1644666849-912006174-747199667-1001';$script:SystemSid='S-1-5-18';$script:AdministratorsSid='S-1-5-32-544'
$script:Confirmation='EXECUTE_ACEL_G1_GROUP4_PARTY_B_WRITE_V1';$script:RegistryRelative='governance/sources/issuer_registry/REGISTRY.json';$script:ResponseRelative='governance/sources/issuer_registry/LOOKUP_RESPONSES.jsonl';$script:ObservationRelative='governance/sources/registry_observation_log/LOG.jsonl';$script:ScriptPath=$PSCommandPath;$script:Tests=[Collections.Generic.List[object]]::new()

function Stop-Writer([string]$Code,[string]$Message){throw [InvalidOperationException]::new("${Code}: ${Message}")}
function Get-CanonicalPath([string]$Path){[IO.Path]::GetFullPath($Path).TrimEnd([IO.Path]::DirectorySeparatorChar)}
function Assert-NoReparseTraversal([string]$BasePath,[string]$CandidatePath){$base=Get-CanonicalPath $BasePath;$candidate=Get-CanonicalPath $CandidatePath;$prefix=$base+[IO.Path]::DirectorySeparatorChar;if($candidate-cne$base-and-not$candidate.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){Stop-Writer 'TEST_CONTAINMENT_VIOLATION' $candidate};$current=$base;if(Test-Path -LiteralPath $current){$item=Get-Item -LiteralPath $current -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){Stop-Writer 'TEST_CONTAINMENT_VIOLATION' ('reparse traversal: '+$current)}};if($candidate-cne$base){foreach($part in $candidate.Substring($prefix.Length)-split'[\\/]'){$current=Join-Path $current $part;if(Test-Path -LiteralPath $current){$item=Get-Item -LiteralPath $current -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){Stop-Writer 'TEST_CONTAINMENT_VIOLATION' ('reparse traversal: '+$current)}}}}}
function Get-Sha256Hex([byte[]]$Bytes){$s=[Security.Cryptography.SHA256]::Create();try{([Convert]::ToHexString($s.ComputeHash($Bytes))).ToLowerInvariant()}finally{$s.Dispose()}}
function Test-BytesEqual([byte[]]$Left,[byte[]]$Right){if($null-eq$Left-or$null-eq$Right-or$Left.Length-ne$Right.Length){return $false};for($i=0;$i-lt$Left.Length;$i++){if($Left[$i]-ne$Right[$i]){return $false}};return $true}
function Get-MutexName([string]$Target){'Global\CVF_G4_RESPONSE_TXN_'+(Get-Sha256Hex ([Text.Encoding]::UTF8.GetBytes((Get-CanonicalPath $Target).ToUpperInvariant()))).Substring(0,48)}
function Resolve-PythonRuntime([string]$ExplicitPath){if($ExplicitPath){$resolved=Get-CanonicalPath $ExplicitPath;if(-not(Test-Path -LiteralPath $resolved -PathType Leaf)){Stop-Writer 'PYTHON_EXECUTABLE_UNAVAILABLE' $resolved};$prefix=if([IO.Path]::GetFileNameWithoutExtension($resolved)-ieq'py'){@('-3')}else{@()}}else{$command=Get-Command py -ErrorAction SilentlyContinue;$prefix=@('-3');if($null-eq$command){$command=Get-Command python -ErrorAction SilentlyContinue;$prefix=@()};if($null-eq$command){Stop-Writer 'PYTHON_EXECUTABLE_UNAVAILABLE' 'neither py nor python resolved'};$resolved=$command.Source};$probe=&$resolved @prefix --version 2>&1;if($LASTEXITCODE-ne0){Stop-Writer 'PYTHON_EXECUTABLE_UNUSABLE' ($probe-join"`n")};[pscustomobject]@{executable=$resolved;prefix=@($prefix)}}
function Invoke-PythonRuntime($Runtime,[string[]]$Arguments){$exe=[string]$Runtime.executable;$prefix=@($Runtime.prefix);$out=&$exe @prefix @Arguments 2>&1;[pscustomobject]@{exitCode=$LASTEXITCODE;output=@($out)}}
function Assert-DisposableFixtureRoot([string]$Path){$full=Get-CanonicalPath $Path;$tempRoot=Get-CanonicalPath([IO.Path]::GetTempPath());$temp=$tempRoot+[IO.Path]::DirectorySeparatorChar;if(-not$full.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase)){Stop-Writer 'TEST_CONTAINMENT_VIOLATION' $full};$first=(($full.Substring($temp.Length))-split'[\\/]')[0];if($first-notlike'cvf-g4b-*'){Stop-Writer 'TEST_CONTAINMENT_VIOLATION' $full};Assert-NoReparseTraversal $tempRoot $full;$full}
function Enter-Guard([string]$Target,[switch]$InjectAfterAcquire,[Threading.EventWaitHandle]$AcquiredEvent){$m=$null;$held=$false;try{$created=$false;$m=[Threading.Mutex]::new($false,(Get-MutexName $Target),[ref]$created);try{$held=$m.WaitOne(15000)}catch [Threading.AbandonedMutexException]{$held=$true};if(-not$held){Stop-Writer 'CONCURRENCY_TIMEOUT' 'guard timeout'};if($null-ne$AcquiredEvent){$AcquiredEvent.Set()|Out-Null};if($InjectAfterAcquire){Stop-Writer 'ROLLBACK_INJECTED_AFTER_ACQUIRE' 'self-test injection'};return $m}catch{if($null-ne$m){if($held){try{$m.ReleaseMutex()}catch{}};$m.Dispose()};throw}}
function Exit-Guard($Mutex){if($null-ne$Mutex){try{$Mutex.ReleaseMutex()}finally{$Mutex.Dispose()}}}

function Get-ExpectedAceVector([switch]$TestPolicy){$full=[int][Security.AccessControl.FileSystemRights]::FullControl;$probe=[Security.AccessControl.FileSystemAccessRule]::new([Security.Principal.SecurityIdentifier]::new($script:LocalSid),[Security.AccessControl.FileSystemRights]::Read,[Security.AccessControl.AccessControlType]::Allow);$read=[int]$probe.FileSystemRights;if($TestPolicy){$current=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;return @([pscustomobject]@{sid=$current;rights=$full;accessType=0;isInherited=$false;inheritanceFlags=0;propagationFlags=0})};@([pscustomobject]@{sid=$script:PartyBSid;rights=$full;accessType=0;isInherited=$false;inheritanceFlags=0;propagationFlags=0},[pscustomobject]@{sid=$script:SystemSid;rights=$full;accessType=0;isInherited=$false;inheritanceFlags=0;propagationFlags=0},[pscustomobject]@{sid=$script:AdministratorsSid;rights=$full;accessType=0;isInherited=$false;inheritanceFlags=0;propagationFlags=0},[pscustomobject]@{sid=$script:LocalSid;rights=$read;accessType=0;isInherited=$false;inheritanceFlags=0;propagationFlags=0})}
function Get-SecurityState([string]$Path){$sections=[Security.AccessControl.AccessControlSections]::Owner-bor[Security.AccessControl.AccessControlSections]::Access;$s=[IO.FileSystemAclExtensions]::GetAccessControl([IO.FileInfo]::new($Path),$sections);$aces=@($s.GetAccessRules($true,$true,[Security.Principal.SecurityIdentifier])|ForEach-Object{[pscustomobject]@{sid=$_.IdentityReference.Value;rights=[int]$_.FileSystemRights;accessType=[int]$_.AccessControlType;isInherited=[bool]$_.IsInherited;inheritanceFlags=[int]$_.InheritanceFlags;propagationFlags=[int]$_.PropagationFlags}});[pscustomobject]@{ownerSid=$s.GetOwner([Security.Principal.SecurityIdentifier]).Value;protectionState=[bool]$s.AreAccessRulesProtected;aces=$aces;raw=$s;binary=$s.GetSecurityDescriptorBinaryForm()}}
function Get-OrderedTupleStrings($State){@($State.aces|ForEach-Object{'{0}|{1}|{2}|{3}|{4}|{5}'-f$_.sid,$_.rights,$_.accessType,$_.isInherited,$_.inheritanceFlags,$_.propagationFlags})}
function Get-SemanticTupleStrings($State){@(Get-OrderedTupleStrings $State|Sort-Object -CaseSensitive)}
function Test-SecurityStateExact($State,[string]$Owner,[bool]$Protection,[object[]]$Aces){if($State.ownerSid-cne$Owner-or$State.protectionState-ne$Protection){return $false};$expected=[pscustomobject]@{aces=$Aces};if(((Get-OrderedTupleStrings $State)-join"`n")-cne((Get-OrderedTupleStrings $expected)-join"`n")){return $false};((Get-SemanticTupleStrings $State)-join"`n")-ceq((Get-SemanticTupleStrings $expected)-join"`n")}
function Test-SecurityModel($State,[string]$Owner,[object[]]$Aces){Test-SecurityStateExact $State $Owner $true $Aces}
function Assert-Security([string]$Path,[switch]$TestPolicy){$a=Get-SecurityState $Path;$e=@(Get-ExpectedAceVector -TestPolicy:$TestPolicy);$owner=if($TestPolicy){$e[0].sid}else{$script:PartyBSid};if(-not(Test-SecurityModel $a $owner $e)){Stop-Writer 'SECURITY_STATE_MISMATCH' 'owner/protection/ordered complete ACE vector or semantic multiset differs'};$a}
function Set-ExactSecurity([string]$Path,[switch]$TestPolicy){$e=@(Get-ExpectedAceVector -TestPolicy:$TestPolicy);$s=[Security.AccessControl.FileSecurity]::new();$s.SetAccessRuleProtection($true,$false);$owner=if($TestPolicy){$e[0].sid}else{$script:PartyBSid};$s.SetOwner([Security.Principal.SecurityIdentifier]::new($owner));foreach($ace in $e){$s.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new([Security.Principal.SecurityIdentifier]::new($ace.sid),[Security.AccessControl.FileSystemRights]$ace.rights,[Security.AccessControl.InheritanceFlags]$ace.inheritanceFlags,[Security.AccessControl.PropagationFlags]$ace.propagationFlags,[Security.AccessControl.AccessControlType]$ace.accessType))};[IO.FileSystemAclExtensions]::SetAccessControl([IO.FileInfo]::new($Path),$s);Assert-Security $Path -TestPolicy:$TestPolicy|Out-Null}
function Write-HardenedTemp([string]$Directory,[string]$Prefix,[byte[]]$Bytes,[switch]$TestPolicy,[switch]$InjectHardeningFailure){$path=Join-Path $Directory ($Prefix+[Guid]::NewGuid().ToString('N')+'.tmp');try{$stream=[IO.FileStream]::new($path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None,4096,[IO.FileOptions]::WriteThrough);try{if($Bytes.Length){$stream.Write($Bytes,0,$Bytes.Length)};$stream.Flush($true)}finally{$stream.Dispose()};if($InjectHardeningFailure){Stop-Writer 'HARDENING_INJECTED_FAILURE' 'self-test'};Set-ExactSecurity $path -TestPolicy:$TestPolicy;if(-not(Test-BytesEqual ([IO.File]::ReadAllBytes($path)) $Bytes)){Stop-Writer 'HASH_TEMP_READBACK_MISMATCH' $path};return $path}catch{if(Test-Path -LiteralPath $path){Remove-Item -LiteralPath $path -Force};throw}}
function Remove-OrphanTemps([string]$Directory){if(-not(Test-Path $Directory -PathType Container)){return};foreach($pattern in @('.cvf-g4-response-*.tmp','.cvf-g4-capture-*.tmp','.cvf-g4-rollback-*.tmp')){foreach($item in @(Get-ChildItem -LiteralPath $Directory -File -Force -Filter $pattern)){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){Stop-Writer 'ROLLBACK_ORPHAN_REPARSE_POINT' $item.FullName};Remove-Item -LiteralPath $item.FullName -Force}}}
function Wait-CrashBarrier([string]$Point,[string]$Selected,[Threading.EventWaitHandle]$Event){if($Point-ceq$Selected-and$null-ne$Event){$Event.Set()|Out-Null;[Threading.Thread]::Sleep([Threading.Timeout]::Infinite)}}
function Restore-ExistingAtomic([string]$Target,[byte[]]$Bytes,$Security,[switch]$TestPolicy){$dir=Split-Path -Parent $Target;$rollback=Write-HardenedTemp $dir '.cvf-g4-rollback-' $Bytes -TestPolicy:$TestPolicy;try{$descriptor=[Security.AccessControl.FileSecurity]::new();$sections=[Security.AccessControl.AccessControlSections]::Owner-bor[Security.AccessControl.AccessControlSections]::Access;$descriptor.SetSecurityDescriptorBinaryForm($Security.binary,$sections);[IO.FileSystemAclExtensions]::SetAccessControl([IO.FileInfo]::new($rollback),$descriptor);$state=Get-SecurityState $rollback;if(-not(Test-BytesEqual ([IO.File]::ReadAllBytes($rollback)) $Bytes)-or-not(Test-SecurityStateExact $state $Security.ownerSid $Security.protectionState $Security.aces)){Stop-Writer 'ROLLBACK_TEMP_MISMATCH' $rollback};[IO.File]::Move($rollback,$Target,$true);$rollback=$null;$actual=Get-SecurityState $Target;if(-not(Test-BytesEqual ([IO.File]::ReadAllBytes($Target)) $Bytes)-or-not(Test-SecurityStateExact $actual $Security.ownerSid $Security.protectionState $Security.aces)){Stop-Writer 'ROLLBACK_TARGET_MISMATCH' $Target}}finally{if($null-ne$rollback-and(Test-Path $rollback)){Remove-Item -LiteralPath $rollback -Force}}}

function Write-CopyOnWriteTransaction([string]$Target,[byte[]]$FinalBytes,[ValidateSet('None','AfterAcquire','AfterTempFlush','BeforeReplace','AfterReplace')][string]$InjectFailure='None',[switch]$RequireAbsent,[switch]$TestPolicy,$ParentBarrierEvents,[Threading.EventWaitHandle]$AcquiredEvent,[Threading.EventWaitHandle]$RequiredParentReleaseEvent,[ValidateSet('None','AfterAcquireBeforeMutation','AfterTempFlush','BeforeReplace')][string]$CrashAt='None',[Threading.EventWaitHandle]$CrashEvent,[string]$RegistryPath,[string]$CheckerPath,$PythonRuntime,[byte[]]$InjectCompetitorBytes){
 $guard=$null;$temp=$null;$capture=$null;$dir=Split-Path -Parent $Target;$guardAcquired=$false;$prestateCaptured=$false;$publishedByTransaction=$false;$dirExisted=$false;$existed=$false;$prior=$null;$security=$null
 try{$guard=Enter-Guard $Target -InjectAfterAcquire:($InjectFailure-eq'AfterAcquire') -AcquiredEvent $AcquiredEvent;$guardAcquired=$true;if($null-ne$RequiredParentReleaseEvent-and-not$RequiredParentReleaseEvent.WaitOne(0)){Stop-Writer 'CONCURRENCY_ENTERED_BEFORE_PARENT_RELEASE' 'peer acquired before release'};$dirExisted=Test-Path $dir;$existed=Test-Path $Target;if($existed){$prior=[IO.File]::ReadAllBytes($Target);$security=Get-SecurityState $Target};$prestateCaptured=$true;Wait-CrashBarrier 'AfterAcquireBeforeMutation' $CrashAt $CrashEvent;if($RequireAbsent-and$existed){Stop-Writer 'RESPONSE_LOG_ALREADY_EXISTS' 'initializer is create-only'};[IO.Directory]::CreateDirectory($dir)|Out-Null;Remove-OrphanTemps $dir
  if($RegistryPath){if($null-eq$PythonRuntime){Stop-Writer 'PYTHON_EXECUTABLE_UNAVAILABLE' 'registry validation requires resolved runtime'};$registryBytes=[IO.File]::ReadAllBytes($RegistryPath);$capture=Write-HardenedTemp $dir '.cvf-g4-capture-' $registryBytes -TestPolicy:$TestPolicy;$validation=Invoke-PythonRuntime $PythonRuntime @($CheckerPath,'--registry',$capture);if($validation.exitCode-ne0){Stop-Writer 'SOURCE_SCHEMA_INVALID' ('exact captured registry bytes rejected inside guard: '+($validation.output-join"`n"))}}
  $temp=Write-HardenedTemp $dir '.cvf-g4-response-' $FinalBytes -TestPolicy:$TestPolicy;Wait-CrashBarrier 'AfterTempFlush' $CrashAt $CrashEvent;if($InjectFailure-eq'AfterTempFlush'){Stop-Writer 'ROLLBACK_INJECTED_AFTER_TEMP_FLUSH' 'self-test'}
  if($null-ne$ParentBarrierEvents){$ParentBarrierEvents.StartAttempt.Set()|Out-Null;if(-not$ParentBarrierEvents.Attempting.WaitOne(15000)){Stop-Writer 'CONCURRENCY_PEER_NOT_ATTEMPTING' 'ATTEMPTING not observed'};if($ParentBarrierEvents.Entered.WaitOne(0)){Stop-Writer 'CONCURRENCY_ENTERED_BEFORE_PARENT_RELEASE' 'peer entered while parent held guard'}}
  Wait-CrashBarrier 'BeforeReplace' $CrashAt $CrashEvent;if($InjectFailure-eq'BeforeReplace'){Stop-Writer 'ROLLBACK_INJECTED_BEFORE_REPLACE' 'self-test'};if($null-ne$InjectCompetitorBytes){[IO.File]::WriteAllBytes($Target,$InjectCompetitorBytes)};[IO.File]::Move($temp,$Target,$existed);$temp=$null;$publishedByTransaction=$true;if($InjectFailure-eq'AfterReplace'){Stop-Writer 'ROLLBACK_INJECTED_AFTER_REPLACE' 'self-test'};if(-not(Test-BytesEqual ([IO.File]::ReadAllBytes($Target)) $FinalBytes)){Stop-Writer 'HASH_TARGET_READBACK_MISMATCH' $Target};Assert-Security $Target -TestPolicy:$TestPolicy|Out-Null;if($null-ne$ParentBarrierEvents){$ParentBarrierEvents.ParentRelease.Set()|Out-Null}
 }catch{$primary=$_;if($guardAcquired-and$prestateCaptured-and$publishedByTransaction){try{if($existed){Restore-ExistingAtomic $Target $prior $security -TestPolicy:$TestPolicy}elseif(Test-Path $Target){Remove-Item -LiteralPath $Target -Force}}catch{Stop-Writer 'ROLLBACK_FAILED' ($primary.Exception.Message+' | '+$_.Exception.Message)}};if($null-ne$ParentBarrierEvents){$ParentBarrierEvents.ParentRelease.Set()|Out-Null};throw $primary
 }finally{foreach($path in @($temp,$capture)){if($null-ne$path-and(Test-Path $path)){Remove-Item -LiteralPath $path -Force}};if($guardAcquired-and$prestateCaptured-and-not$dirExisted-and(Test-Path $dir)-and@(Get-ChildItem $dir -Force).Count-eq0){Remove-Item -LiteralPath $dir -Force};Exit-Guard $guard}
}

function Assert-PrincipalAndPaths([string]$Root,[string]$Confirm){$id=[Security.Principal.WindowsIdentity]::GetCurrent();if($id.Name-cne$script:PartyBAccount-or$id.User.Value-cne$script:PartyBSid){Stop-Writer 'ACCESS_PRINCIPAL_MISMATCH' 'exact Party B account/SID required'};if($Confirm-cne$script:Confirmation){Stop-Writer 'ACCESS_CONFIRMATION_MISMATCH' 'exact confirmation required'};$r=Get-CanonicalPath $Root;$git=&git -C $r rev-parse --show-toplevel 2>$null;if($LASTEXITCODE-ne0-or(Get-CanonicalPath $git)-cne$r){Stop-Writer 'ACCESS_REPOSITORY_ROOT_INVALID' 'canonical Git root required'};[pscustomobject]@{root=$r;registry=Get-CanonicalPath(Join-Path $r $script:RegistryRelative);responses=Get-CanonicalPath(Join-Path $r $script:ResponseRelative);observations=Get-CanonicalPath(Join-Path $r $script:ObservationRelative);checker=Get-CanonicalPath(Join-Path $r 'governance/compat/check_acel_g1_issuer_registry.py')}}
function Get-PreparedResponseLine($PythonRuntime,[string]$Checker,[string]$Registry,[string]$Responses,[string]$Observations,[string]$Request){$run=Invoke-PythonRuntime $PythonRuntime @($Checker,'--registry',$Registry,'--responses',$Responses,'--observation-log',$Observations,'--prepare-request',$Request);try{$payload=($run.output-join"`n"|ConvertFrom-Json)}catch{Stop-Writer 'LOOKUP_PREPARATION_FAILED' 'checker returned non-JSON output'};if($run.exitCode-ne0){$code=if($payload.taxonomyId){[string]$payload.taxonomyId}else{'LOOKUP_PREPARATION_FAILED'};Stop-Writer $code ([string]$payload.message)};$payload}
function Invoke-LookupAppendTransaction($Paths,[string]$Request,$PythonRuntime,[switch]$TestPolicy,$ParentBarrierEvents,[Threading.EventWaitHandle]$AcquiredEvent,[Threading.EventWaitHandle]$RequiredParentReleaseEvent,[ValidateSet('None','AfterAcquireBeforeMutation','AfterTempFlush','BeforeReplace')][string]$CrashAt='None',[Threading.EventWaitHandle]$CrashEvent){$guard=$null;$dir=Split-Path -Parent $Paths.responses;$temps=[Collections.Generic.List[string]]::new();$publishedByTransaction=$false;$prior=$null;$security=$null;try{$guard=Enter-Guard $Paths.responses -AcquiredEvent $AcquiredEvent;if($null-ne$RequiredParentReleaseEvent-and-not$RequiredParentReleaseEvent.WaitOne(0)){Stop-Writer 'CONCURRENCY_ENTERED_BEFORE_PARENT_RELEASE' 'append peer acquired before release'};if(-not(Test-Path $Paths.responses)-or-not(Test-Path $Paths.registry)-or-not(Test-Path $Paths.observations)-or-not(Test-Path $Request)){Stop-Writer 'SOURCE_UNAVAILABLE' 'response, registry, observation, and request required'};$prior=[IO.File]::ReadAllBytes($Paths.responses);$security=Assert-Security $Paths.responses -TestPolicy:$TestPolicy;Wait-CrashBarrier 'AfterAcquireBeforeMutation' $CrashAt $CrashEvent;Remove-OrphanTemps $dir
 $registryCapture=Write-HardenedTemp $dir '.cvf-g4-capture-' ([IO.File]::ReadAllBytes($Paths.registry)) -TestPolicy:$TestPolicy;$temps.Add($registryCapture);$responseCapture=Write-HardenedTemp $dir '.cvf-g4-capture-' $prior -TestPolicy:$TestPolicy;$temps.Add($responseCapture);$observationCapture=Write-HardenedTemp $dir '.cvf-g4-capture-' ([IO.File]::ReadAllBytes($Paths.observations)) -TestPolicy:$TestPolicy;$temps.Add($observationCapture);$requestCapture=Write-HardenedTemp $dir '.cvf-g4-capture-' ([IO.File]::ReadAllBytes($Request)) -TestPolicy:$TestPolicy;$temps.Add($requestCapture)
 $prepared=Get-PreparedResponseLine $PythonRuntime $Paths.checker $registryCapture $responseCapture $observationCapture $requestCapture;if($prepared.kind-ceq'IDEMPOTENT'){return [pscustomobject]@{result='IDEMPOTENT';row=$prepared.row}};$line=[Convert]::FromBase64String([string]$prepared.lineBase64);$final=[byte[]]($prior+$line);$candidate=Write-HardenedTemp $dir '.cvf-g4-response-' $final -TestPolicy:$TestPolicy;$temps.Add($candidate);Wait-CrashBarrier 'AfterTempFlush' $CrashAt $CrashEvent
 $candidateCheck=Invoke-PythonRuntime $PythonRuntime @($Paths.checker,'--registry',$registryCapture,'--responses',$candidate,'--observation-log',$observationCapture,'--receipt-context');if($candidateCheck.exitCode-ne0){Stop-Writer 'CHAIN_VALIDATION_FAILED' ('candidate rejected: '+($candidateCheck.output-join"`n"))};if($null-ne$ParentBarrierEvents){$ParentBarrierEvents.StartAttempt.Set()|Out-Null;if(-not$ParentBarrierEvents.Attempting.WaitOne(15000)){Stop-Writer 'CONCURRENCY_PEER_NOT_ATTEMPTING' 'append peer did not attempt'};if($ParentBarrierEvents.Entered.WaitOne(0)){Stop-Writer 'CONCURRENCY_ENTERED_BEFORE_PARENT_RELEASE' 'append peer entered while parent held guard'}};Wait-CrashBarrier 'BeforeReplace' $CrashAt $CrashEvent
 [IO.File]::Move($candidate,$Paths.responses,$true);$publishedByTransaction=$true;$temps.Remove($candidate)|Out-Null;if(-not(Test-BytesEqual ([IO.File]::ReadAllBytes($Paths.responses)) $final)){Stop-Writer 'HASH_TARGET_READBACK_MISMATCH' $Paths.responses};Assert-Security $Paths.responses -TestPolicy:$TestPolicy|Out-Null;$targetCheck=Invoke-PythonRuntime $PythonRuntime @($Paths.checker,'--registry',$registryCapture,'--responses',$Paths.responses,'--observation-log',$observationCapture,'--receipt-context');if($targetCheck.exitCode-ne0){Stop-Writer 'CHAIN_VALIDATION_FAILED' ('target rejected: '+($targetCheck.output-join"`n"))};if($null-ne$ParentBarrierEvents){$ParentBarrierEvents.ParentRelease.Set()|Out-Null};[pscustomobject]@{result='APPENDED_PENDING_LOCAL_VERIFICATION';row=$prepared.row}
 }catch{$primary=$_;if($publishedByTransaction){try{Restore-ExistingAtomic $Paths.responses $prior $security -TestPolicy:$TestPolicy}catch{Stop-Writer 'ROLLBACK_FAILED' ($primary.Exception.Message+' | '+$_.Exception.Message)}};if($null-ne$ParentBarrierEvents){$ParentBarrierEvents.ParentRelease.Set()|Out-Null};throw $primary}finally{foreach($temp in @($temps)){if(Test-Path $temp){Remove-Item -LiteralPath $temp -Force}};Exit-Guard $guard}}

function New-PeerEvents([string]$Run){$m=[Threading.EventResetMode]::ManualReset;[pscustomobject]@{Ready=[Threading.EventWaitHandle]::new($false,$m,"Local\CVF_G4B_READY_$Run");StartAttempt=[Threading.EventWaitHandle]::new($false,$m,"Local\CVF_G4B_START_ATTEMPT_$Run");Attempting=[Threading.EventWaitHandle]::new($false,$m,"Local\CVF_G4B_ATTEMPTING_$Run");ParentRelease=[Threading.EventWaitHandle]::new($false,$m,"Local\CVF_G4B_PARENT_RELEASE_$Run");Entered=[Threading.EventWaitHandle]::new($false,$m,"Local\CVF_G4B_ENTERED_$Run");Complete=[Threading.EventWaitHandle]::new($false,$m,"Local\CVF_G4B_COMPLETE_$Run")}}
function Get-TestFixturePaths([string]$Root){$rootPath=Assert-DisposableFixtureRoot $Root;$p=[pscustomobject]@{root=$rootPath;registry=Join-Path $rootPath 'REGISTRY.json';responses=Join-Path $rootPath 'LOOKUP_RESPONSES.jsonl';observations=Join-Path $rootPath 'LOG.jsonl';request=Join-Path $rootPath 'REQUEST.json';checker=Join-Path (Split-Path -Parent (Split-Path -Parent $script:ScriptPath)) 'governance/compat/check_acel_g1_issuer_registry.py'};foreach($path in @($p.registry,$p.responses,$p.observations,$p.request)){if(Test-Path -LiteralPath $path){$item=Get-Item -LiteralPath $path -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint-or$item.Length-gt1048576){Stop-Writer 'TEST_CONTAINMENT_VIOLATION' ('invalid fixture: '+$path)}}};$p}
function New-LookupFixture([string]$Root,[byte[]]$RegistryBytes){
 $p=Get-TestFixturePaths $Root;[IO.Directory]::CreateDirectory($p.root)|Out-Null;[IO.File]::WriteAllBytes($p.registry,$RegistryBytes);[IO.File]::WriteAllBytes($p.responses,[byte[]]::new(0));Set-ExactSecurity $p.responses -TestPolicy
 $snapshotHash=Get-Sha256Hex $RegistryBytes;$snapshotContent=[Convert]::ToBase64String($RegistryBytes).TrimEnd('=').Replace('+','-').Replace('/','_');$observed=[DateTime]::UtcNow.AddSeconds(-1).ToString('yyyy-MM-ddTHH:mm:ssZ');$snapshotId='snap-issuer-001'
 $preimage='{"authority":"ACEL_G1_DECISION_OWNER","domain":"cvf.observationLogEntry","observedAt":"'+$observed+'","observerIdentity":"'+$script:PartyBSid+'","priorEntryHashHex":null,"profile":"cvf.source-record-canonicalization@1","registryName":"issuer_registry","registrySnapshotVersion":1,"snapshotHashHex":"'+$snapshotHash+'","snapshotId":"'+$snapshotId+'"}'
 $entryHash=Get-Sha256Hex ([Text.Encoding]::UTF8.GetBytes($preimage));$record='{"authority":"ACEL_G1_DECISION_OWNER","entryHashHex":"'+$entryHash+'","observedAt":"'+$observed+'","observerIdentity":"'+$script:PartyBSid+'","priorEntryHashHex":null,"registryName":"issuer_registry","registrySnapshotVersion":1,"snapshotHashHex":"'+$snapshotHash+'","snapshotId":"'+$snapshotId+'","snapshot_content":"'+$snapshotContent+'"}'
 [IO.File]::WriteAllBytes($p.observations,[Text.Encoding]::UTF8.GetBytes($record+"`n"));$request='{"claimedIssuerHash":"db76dcc22fcec9cc566c5b449b0aaa8eabdb657d157c62cba626aba8b26d12ca","consumerIdentity":"consumer-test-001","issuerIdentity":"issuer-test-001","lookupId":"808e5a61-0b1c-4bdd-b505-2c2687496b9f","observedSnapshotId":"'+$snapshotId+'"}';[IO.File]::WriteAllBytes($p.request,[Text.Encoding]::UTF8.GetBytes($request));$p
}
function Invoke-PeerMode{$p=Get-TestFixturePaths $PeerFixtureRoot;$python=Resolve-PythonRuntime;$e=New-PeerEvents $PeerRunId;try{$e.Ready.Set()|Out-Null;if(-not$e.StartAttempt.WaitOne(15000)){exit 31};$e.Attempting.Set()|Out-Null;$result=Invoke-LookupAppendTransaction $p $p.request $python -TestPolicy -AcquiredEvent $e.Entered -RequiredParentReleaseEvent $e.ParentRelease;$expected=if($PeerExpectAppend){'APPENDED_PENDING_LOCAL_VERIFICATION'}else{'IDEMPOTENT'};if($result.result-cne$expected){exit 33};$e.Complete.Set()|Out-Null;exit 0}finally{@($e.psobject.Properties.Value)|ForEach-Object{$_.Dispose()}}}
function Invoke-CrashMode{$p=Get-TestFixturePaths $CrashFixtureRoot;$python=Resolve-PythonRuntime;$e=[Threading.EventWaitHandle]::new($false,[Threading.EventResetMode]::ManualReset,"Local\CVF_G4B_CRASH_$CrashRunId");try{Invoke-LookupAppendTransaction $p $p.request $python -TestPolicy -CrashAt $CrashPoint -CrashEvent $e|Out-Null;exit 41}finally{$e.Dispose()}}
function Add-Test([string]$Id,[bool]$Passed,[string]$Detail){$script:Tests.Add([pscustomobject]@{id=$Id;passed=$Passed;detail=$Detail});if(-not$Passed){Stop-Writer 'SELF_TEST_FAILED' "${Id}: ${Detail}"}}
function Test-StrictJsonlFraming([byte[]]$Bytes){if($Bytes.Length-eq0){return $true};if($Bytes.Length-ge3-and$Bytes[0]-eq0xef-and$Bytes[1]-eq0xbb-and$Bytes[2]-eq0xbf){return $false};try{$text=[Text.UTF8Encoding]::new($false,$true).GetString($Bytes)}catch{return $false};if($text.Contains("`r")-or-not$text.EndsWith("`n")){return $false};$lines=$text.Substring(0,$text.Length-1)-split"`n";@($lines|Where-Object{$_.Length-eq0}).Count-eq0}

function Set-AdversarialSecurity([string]$Path,[ValidateSet('EXTRA_ALLOW','DENY','INHERITED','WRONG_OWNER','UNPROTECTED')][string]$Kind){
 $current=[Security.Principal.WindowsIdentity]::GetCurrent().User
 if($Kind-eq'INHERITED'){
  $directory=Split-Path -Parent $Path;$ds=[Security.AccessControl.DirectorySecurity]::new();$ds.SetOwner($current);$ds.SetAccessRuleProtection($true,$false);$ds.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($current,[Security.AccessControl.FileSystemRights]::FullControl,[Security.AccessControl.InheritanceFlags]'ContainerInherit, ObjectInherit',[Security.AccessControl.PropagationFlags]::None,[Security.AccessControl.AccessControlType]::Allow));[IO.FileSystemAclExtensions]::SetAccessControl([IO.DirectoryInfo]::new($directory),$ds);$s=[Security.AccessControl.FileSecurity]::new();$s.SetOwner($current);$s.SetAccessRuleProtection($false,$false);[IO.FileSystemAclExtensions]::SetAccessControl([IO.FileInfo]::new($Path),$s);return
 }
 $state=Get-SecurityState $Path;$s=$state.raw
 switch($Kind){
  'EXTRA_ALLOW'{$s.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new([Security.Principal.SecurityIdentifier]::new($script:SystemSid),[Security.AccessControl.FileSystemRights]::Read,[Security.AccessControl.AccessControlType]::Allow))}
  'DENY'{$s.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new([Security.Principal.SecurityIdentifier]::new($script:SystemSid),[Security.AccessControl.FileSystemRights]::Read,[Security.AccessControl.AccessControlType]::Deny))}
  'WRONG_OWNER'{$s.SetOwner([Security.Principal.SecurityIdentifier]::new($script:AdministratorsSid))}
  'UNPROTECTED'{$s.SetAccessRuleProtection($false,$true)}
 }
 [IO.FileSystemAclExtensions]::SetAccessControl([IO.FileInfo]::new($Path),$s)
}

function Invoke-SelfTest{
 $root=Join-Path ([IO.Path]::GetTempPath()) ('cvf-g4b-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null
 try{
  $python=Resolve-PythonRuntime;$registryBytes=[Text.Encoding]::UTF8.GetBytes('{"registrySnapshotId":"issuer-registry-snapshot-test-0001","registrySnapshotVersion":1,"rows":[{"canonicalContentBytesBase64":"eyJhdXRob3JpdHkiOiJBQ0VMX0cxX0RFQ0lTSU9OX09XTkVSIiwiaXNzdWVySWRlbnRpdHkiOiJpc3N1ZXItdGVzdC0wMDEiLCJwb2xpY3lWZXJzaW9uIjoxfQ","canonicalContentHashHex":"db76dcc22fcec9cc566c5b449b0aaa8eabdb657d157c62cba626aba8b26d12ca","correctedAt":null,"entryVersion":1,"issuerAttestedHash":"db76dcc22fcec9cc566c5b449b0aaa8eabdb657d157c62cba626aba8b26d12ca","issuerIdentity":"issuer-test-001","registeredAt":"2026-09-22T00:00:00Z","revokedAt":null,"status":"ACTIVE"}],"writeTimestamp":"2026-09-22T00:00:01Z"}')
  $target=Join-Path $root 'source/LOOKUP_RESPONSES.jsonl';Write-CopyOnWriteTransaction $target ([byte[]]::new(0)) -RequireAbsent -TestPolicy;Add-Test 'T3D-C1-B-01' ((Test-Path $target)-and([IO.File]::ReadAllBytes($target).Length-eq0)) 'zero-byte initialization';$prefix=[Text.Encoding]::UTF8.GetBytes("{`"entry`":1}`n");Write-CopyOnWriteTransaction $target $prefix -TestPolicy;$second=[Text.Encoding]::UTF8.GetBytes("{`"entry`":2}`n");$multi=[byte[]]($prefix+$second);Write-CopyOnWriteTransaction $target $multi -TestPolicy;Add-Test 'T3D-C1-B-02' (Test-BytesEqual ([IO.File]::ReadAllBytes($target)[0..($prefix.Length-1)]) $prefix) 'prior bytes exact prefix'
  $raceTarget=Join-Path $root 'race/LOOKUP_RESPONSES.jsonl';$competitor=[Text.Encoding]::UTF8.GetBytes('competitor-owned-by-other-actor');try{Write-CopyOnWriteTransaction $raceTarget ([byte[]]::new(0)) -RequireAbsent -TestPolicy -InjectCompetitorBytes $competitor;$racePreserved=$false}catch{$racePreserved=(Test-Path $raceTarget)-and(Test-BytesEqual ([IO.File]::ReadAllBytes($raceTarget)) $competitor)};Add-Test 'T3D-C1-B-INIT-RACE' $racePreserved 'failed no-overwrite move never deletes competitor publication'
  foreach($point in @('AfterAcquire','AfterTempFlush','BeforeReplace','AfterReplace')){$before=[IO.File]::ReadAllBytes($target);$failure='none';try{Write-CopyOnWriteTransaction $target ([Text.Encoding]::UTF8.GetBytes('bad')) -InjectFailure $point -TestPolicy;$failed=$false}catch{$failed=$true;$failure=$_.Exception.Message};Add-Test "T3D-C1-B-ROLLBACK-$point" ($failed-and(Test-BytesEqual ([IO.File]::ReadAllBytes($target)) $before)) ('atomic rollback preserves bytes; '+$failure)}
  $hardeningDir=Join-Path $root 'hardening';[IO.Directory]::CreateDirectory($hardeningDir)|Out-Null;try{Write-HardenedTemp $hardeningDir '.cvf-g4-response-' $prefix -TestPolicy -InjectHardeningFailure|Out-Null;$hardeningFailed=$false}catch{$hardeningFailed=$true};Add-Test 'T3D-C1-B-HARDEN-FAIL' ($hardeningFailed-and@(Get-ChildItem $hardeningDir -Force -Filter '*.tmp').Count-eq0) 'temp helper removes its own artifact when hardening fails'

  $appendRoot=Join-Path $root 'append-peer';$append=New-LookupFixture $appendRoot $registryBytes;$run=[Guid]::NewGuid().ToString('N');$events=New-PeerEvents $run;$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=(Get-Command pwsh).Source;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;foreach($a in @('-NoProfile','-NonInteractive','-File',$script:ScriptPath,'-PeerMode','-PeerRunId',$run,'-PeerFixtureRoot',$appendRoot)){$psi.ArgumentList.Add($a)};$peer=[Diagnostics.Process]::Start($psi)
  try{Add-Test 'T3D-C1-B-PEER-READY' ($events.Ready.WaitOne(15000)) 'READY';$parentResult=Invoke-LookupAppendTransaction $append $append.request $python -TestPolicy -ParentBarrierEvents $events;Add-Test 'T3D-C1-B-PEER-PARENT' ($parentResult.result-ceq'APPENDED_PENDING_LOCAL_VERIFICATION') 'parent executed production append';Add-Test 'T3D-C1-B-PEER-ATTEMPTING' ($events.Attempting.WaitOne(0)) 'peer attempted production append';Add-Test 'T3D-C1-B-PEER-ENTERED' ($events.Entered.WaitOne(15000)) 'peer entered after release';Add-Test 'T3D-C1-B-PEER-COMPLETE' ($events.Complete.WaitOne(15000)) 'peer returned idempotent';$peer.WaitForExit(15000)|Out-Null;Add-Test 'T3D-C1-B-PEER-EXIT' ($peer.HasExited-and$peer.ExitCode-eq0) 'peer exit zero';$rows=@(([Text.Encoding]::UTF8.GetString([IO.File]::ReadAllBytes($append.responses))).TrimEnd("`n")-split"`n");Add-Test 'T3D-C1-B-PEER-ONCE' ($rows.Count-eq1) 'concurrent identical UUID leaves exactly one row'}finally{if(-not$peer.HasExited){$peer.Kill($true)};$peer.Dispose();@($events.psobject.Properties.Value)|ForEach-Object{$_.Dispose()}}

  $releaseRoot=Join-Path $root 'after-acquire-peer';$releasePaths=New-LookupFixture $releaseRoot $registryBytes;try{Write-CopyOnWriteTransaction $releasePaths.responses ([Text.Encoding]::UTF8.GetBytes('bad')) -InjectFailure AfterAcquire -TestPolicy;$injected=$false}catch{$injected=$_.Exception.Message-like'ROLLBACK_INJECTED_AFTER_ACQUIRE:*'};$releaseRun=[Guid]::NewGuid().ToString('N');$releaseEvents=New-PeerEvents $releaseRun;$releasePsi=[Diagnostics.ProcessStartInfo]::new();$releasePsi.FileName=(Get-Command pwsh).Source;$releasePsi.UseShellExecute=$false;$releasePsi.CreateNoWindow=$true;foreach($a in @('-NoProfile','-NonInteractive','-File',$script:ScriptPath,'-PeerMode','-PeerRunId',$releaseRun,'-PeerFixtureRoot',$releaseRoot,'-PeerExpectAppend')){$releasePsi.ArgumentList.Add($a)};$releasePeer=[Diagnostics.Process]::Start($releasePsi);try{Add-Test 'T3D-C1-B-AFTER-ACQUIRE-READY' ($injected-and$releaseEvents.Ready.WaitOne(15000)) 'second process ready after injected acquisition failure';$releaseEvents.ParentRelease.Set()|Out-Null;$releaseEvents.StartAttempt.Set()|Out-Null;Add-Test 'T3D-C1-B-AFTER-ACQUIRE-ENTERED' ($releaseEvents.Entered.WaitOne(15000)) 'second process acquired same-target guard';Add-Test 'T3D-C1-B-AFTER-ACQUIRE-COMPLETE' ($releaseEvents.Complete.WaitOne(15000)) 'second process completed production append';$releasePeer.WaitForExit(15000)|Out-Null;Add-Test 'T3D-C1-B-AFTER-ACQUIRE-EXIT' ($releasePeer.HasExited-and$releasePeer.ExitCode-eq0) 'same-target successor exited zero'}finally{if(-not$releasePeer.HasExited){$releasePeer.Kill($true)};$releasePeer.Dispose();@($releaseEvents.psobject.Properties.Value)|ForEach-Object{$_.Dispose()}}

  foreach($point in @('AfterAcquireBeforeMutation','AfterTempFlush','BeforeReplace')){$crashRoot=Join-Path $root ("append-crash-$point");$crashPaths=New-LookupFixture $crashRoot $registryBytes;$crashRun=[Guid]::NewGuid().ToString('N');$barrier=[Threading.EventWaitHandle]::new($false,[Threading.EventResetMode]::ManualReset,"Local\CVF_G4B_CRASH_$crashRun");$crashPsi=[Diagnostics.ProcessStartInfo]::new();$crashPsi.FileName=(Get-Command pwsh).Source;$crashPsi.UseShellExecute=$false;$crashPsi.CreateNoWindow=$true;foreach($a in @('-NoProfile','-NonInteractive','-File',$script:ScriptPath,'-CrashMode','-CrashRunId',$crashRun,'-CrashFixtureRoot',$crashRoot,'-CrashPoint',$point)){$crashPsi.ArgumentList.Add($a)};$crash=[Diagnostics.Process]::Start($crashPsi);try{Add-Test "T3D-C1-B-CRASH-$point-BARRIER" ($barrier.WaitOne(15000)) 'production append reached barrier';$crash.Kill($true);$crash.WaitForExit(15000)|Out-Null;Add-Test "T3D-C1-B-CRASH-$point-KILLED" $crash.HasExited 'append worker hard terminated';$recovered=Invoke-LookupAppendTransaction $crashPaths $crashPaths.request $python -TestPolicy;Add-Test "T3D-C1-B-CRASH-$point-RECOVER" ($recovered.result-ceq'APPENDED_PENDING_LOCAL_VERIFICATION') 'successor production append recovered';$count=@(([Text.Encoding]::UTF8.GetString([IO.File]::ReadAllBytes($crashPaths.responses))).TrimEnd("`n")-split"`n").Count;Add-Test "T3D-C1-B-CRASH-$point-ONCE" ($count-eq1) 'recovery leaves one complete row';Add-Test "T3D-C1-B-CRASH-$point-CLEAN" (@(Get-ChildItem $crashRoot -Force -Filter '*.tmp').Count-eq0) 'orphan removed'}finally{if(-not$crash.HasExited){$crash.Kill($true)};$crash.Dispose();$barrier.Dispose()}}

  $testOwner=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;foreach($kind in @('EXTRA_ALLOW','DENY','INHERITED','UNPROTECTED')){$caseDir=Join-Path $root ("descriptor-$kind");[IO.Directory]::CreateDirectory($caseDir)|Out-Null;$caseTarget=Join-Path $caseDir 'LOG.jsonl';[IO.File]::WriteAllBytes($caseTarget,$prefix);Set-ExactSecurity $caseTarget -TestPolicy;Set-AdversarialSecurity $caseTarget $kind;$captured=Get-SecurityState $caseTarget;$shapeValid=switch($kind){'EXTRA_ALLOW'{@($captured.aces).Count-gt1}'DENY'{@($captured.aces|Where-Object accessType -eq 1).Count-gt0}'INHERITED'{(-not$captured.protectionState)-and@($captured.aces|Where-Object isInherited).Count-gt0}'UNPROTECTED'{-not$captured.protectionState}};$failureMessage='none';try{Write-CopyOnWriteTransaction $caseTarget $multi -InjectFailure AfterReplace -TestPolicy;$rolled=$false}catch{$failureMessage=$_.Exception.Message;$actual=Get-SecurityState $caseTarget;$rolled=$shapeValid-and(Test-BytesEqual ([IO.File]::ReadAllBytes($caseTarget)) $prefix)-and(Test-SecurityStateExact $actual $captured.ownerSid $captured.protectionState $captured.aces)};Add-Test "T3D-C1-B-DESCRIPTOR-$kind" $rolled ('atomic rollback restored actual adversarial descriptor and bytes; '+$failureMessage)}
  $ownerDir=Join-Path $root 'descriptor-WRONG_OWNER';[IO.Directory]::CreateDirectory($ownerDir)|Out-Null;$ownerTarget=Join-Path $ownerDir 'LOG.jsonl';[IO.File]::WriteAllBytes($ownerTarget,$prefix);Set-ExactSecurity $ownerTarget -TestPolicy;try{Set-AdversarialSecurity $ownerTarget WRONG_OWNER;$ownerDenied=$false;$ownerError='mutation unexpectedly succeeded'}catch{$ownerError=$_.Exception.Message;$ownerAfter=Get-SecurityState $ownerTarget;$ownerDenied=$ownerError-like'*security identifier is not allowed to be the owner*'-and$ownerAfter.ownerSid-ceq$testOwner};Add-Test 'T3D-C1-B-DESCRIPTOR-WRONG_OWNER-CAPABILITY' $ownerDenied ('current token cannot create a distinct-owner fixture; no rollback claim: '+$ownerError)

  $badRoot=Join-Path $root 'bad-security';$badPaths=New-LookupFixture $badRoot $registryBytes;Set-AdversarialSecurity $badPaths.responses EXTRA_ALLOW;$badBefore=[IO.File]::ReadAllBytes($badPaths.responses);$badState=Get-SecurityState $badPaths.responses;try{Invoke-LookupAppendTransaction $badPaths $badPaths.request $python -TestPolicy|Out-Null;$badRejected=$false}catch{$badAfter=Get-SecurityState $badPaths.responses;$badRejected=$_.Exception.Message-like'SECURITY_STATE_MISMATCH:*'-and(Test-BytesEqual ([IO.File]::ReadAllBytes($badPaths.responses)) $badBefore)-and(Test-SecurityStateExact $badAfter $badState.ownerSid $badState.protectionState $badState.aces)};Add-Test 'T3D-C1-B-PRESTATE-SECURITY' $badRejected 'production append rejects widened descriptor before mutation'

  $expected=@(Get-ExpectedAceVector -TestPolicy);$owner=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;$valid=[pscustomobject]@{ownerSid=$owner;protectionState=$true;aces=$expected};Add-Test 'T3D-C1-B-SEC-VALID' (Test-SecurityModel $valid $owner $expected) 'exact model accepted';$wrongOwnerModel=[pscustomobject]@{ownerSid=$script:AdministratorsSid;protectionState=$true;aces=$expected};Add-Test 'T3D-C1-B-SEC-WRONG-OWNER' (-not(Test-SecurityModel $wrongOwnerModel $owner $expected)) 'complete-state oracle rejects non-expected owner';Add-Test 'T3D-C1-B-FRAME-VALID' (Test-StrictJsonlFraming $prefix) 'valid LF accepted';Add-Test 'T3D-C1-B-FRAME-BOM' (-not(Test-StrictJsonlFraming ([byte[]](0xef,0xbb,0xbf)+$prefix))) 'BOM rejected';Add-Test 'T3D-C1-B-FRAME-CRLF' (-not(Test-StrictJsonlFraming ([Text.Encoding]::UTF8.GetBytes("{}`r`n")))) 'CRLF rejected';Add-Test 'T3D-C1-B-FRAME-BLANK' (-not(Test-StrictJsonlFraming ([Text.Encoding]::UTF8.GetBytes("{}`n`n")))) 'blank rejected';Add-Test 'T3D-C1-B-FRAME-PARTIAL' (-not(Test-StrictJsonlFraming ([Text.Encoding]::UTF8.GetBytes('{}')))) 'partial rejected';$checker=Join-Path (Split-Path -Parent (Split-Path -Parent $script:ScriptPath)) 'governance/compat/check_acel_g1_issuer_registry.py';$checkerRun=Invoke-PythonRuntime $python @($checker,'--self-test');Add-Test 'T3D-C1-B-CHECKER-TAXONOMY' ($checkerRun.exitCode-eq0-and($checkerRun.output-join"`n")-like'*"result": "PASS"*') 'executable checker taxonomy suite passed';try{Get-TestFixturePaths (Join-Path (Split-Path -Parent $root) 'outside')|Out-Null;$contained=$false}catch{$contained=$_.Exception.Message-like'TEST_CONTAINMENT_VIOLATION:*'};Add-Test 'T3D-C1-B-CONTAINMENT' $contained 'peer/crash fixture cannot escape disposable root';$junctionOutside=Join-Path ([IO.Path]::GetTempPath()) ('cvf-g4b-junction-target-'+[Guid]::NewGuid().ToString('N'));$junction=Join-Path $root 'nested-junction';[IO.Directory]::CreateDirectory($junctionOutside)|Out-Null;try{New-Item -ItemType Junction -Path $junction -Target $junctionOutside|Out-Null;try{Get-TestFixturePaths (Join-Path $junction 'fixture')|Out-Null;$nestedContained=$false}catch{$nestedContained=$_.Exception.Message-like'TEST_CONTAINMENT_VIOLATION:*'};Add-Test 'T3D-C1-B-NESTED-REPARSE' $nestedContained 'component walk rejects intermediate junction'}finally{if(Test-Path $junction){Remove-Item -LiteralPath $junction -Force};if(Test-Path $junctionOutside){Remove-Item -LiteralPath $junctionOutside -Force}};Add-Test 'T3D-C1-B-DEFAULT' ($PSCmdlet.ParameterSetName-eq'SelfTest') 'default mode self-test';[pscustomobject]@{result='PASS';tests=$script:Tests.Count;peerProtocol=@('READY','START_ATTEMPT','ATTEMPTING','PARENT_RELEASE','ENTERED','COMPLETE');sourceMutation=$false}|ConvertTo-Json -Compress
 }finally{if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force}}
}
if($PSCmdlet.ParameterSetName-eq'Peer'){Invoke-PeerMode}
if($PSCmdlet.ParameterSetName-eq'Crash'){Invoke-CrashMode}
if($PSCmdlet.ParameterSetName-eq'SelfTest'){Invoke-SelfTest;exit 0}
$paths=Assert-PrincipalAndPaths $RepositoryRoot $Confirmation
$python=Resolve-PythonRuntime $PythonExecutablePath
if($PSCmdlet.ParameterSetName-eq'Initialize'){if(-not(Test-Path $paths.registry)){Stop-Writer 'SOURCE_UNAVAILABLE' 'registry required'};Write-CopyOnWriteTransaction -Target $paths.responses -FinalBytes ([byte[]]::new(0)) -RequireAbsent -RegistryPath $paths.registry -CheckerPath $paths.checker -PythonRuntime $python;[pscustomobject]@{result='RESPONSE_LOG_INITIALIZED_PENDING_LOCAL_VERIFICATION';path=$script:ResponseRelative;sha256=(Get-Sha256Hex ([byte[]]::new(0)))}|ConvertTo-Json -Compress;exit 0}
$result=Invoke-LookupAppendTransaction $paths (Get-CanonicalPath $RequestJsonPath) $python;$result|ConvertTo-Json -Depth 8 -Compress
